### ISSUE TITLE
Working Code Provided for External LEDs and Piezo Buzzer with 3.0.1R4 and Crius Board 1.1

### ISSUE THREAD

**Issue by bmizes** [MegaPirateNG/ardupilot-mpng#106]
This post isn't an issue per se but rather a solution to the problem of having External Leds for arm/disarm and gps lock/no lock with 3.0.1R4 and a Crius 1.1 board.  As you may or may not know, the Crius board only has A0-A5 so the code provided in the 3.0.1R4 does not work for this board.  I wanted to post the necessary code changes so that anyone with this board could take advantage of external leds as well as a piezo buzzer. 

in config.h,
# define PIEZO_PIN 46

 #define COPTER_LED_1 AN2         // Motor or Aux LED
 #define COPTER_LED_2 AN3         // Motor LED
 #define COPTER_LED_3 AN4         // Motor or GPS LED
 #define COPTER_LED_4 AN7         // Motor LED
 #define COPTER_LED_5 -1         // Motor LED
 #define COPTER_LED_6 -1         // Motor LED
 #define COPTER_LED_7 -1        // Motor LED
 #define COPTER_LED_8 -1        // Motor LED

in define.h,
# define AN5  46

// #define PIEZO_PIN 32           //Last pin on the back ADC connector
# define PIEZO_PIN 46

in Mission Planner, 
set Led Mode to 127 in Advanced parameters

Then use A3 for the arming led, A4 for the GPS led, and pin 46 for the buzzer.  Works great.  I have to thank spsberg on youtube for his help with these code changes.

**Comment by smurfy** [comment]
Looks like a nice part for a tips and tricks section of the documentation.
If i have time i will create such thing and add this to it too. 

Thank you.

**Comment by smurfy** [comment]
@bmizes Thanks again for your code changes. I just added the changes to the official documentation [tips and tricks section](http://docs.megapirateng.com/documentation/tipsntricks).

If i did not mess up transfering your changes please close this issue. Thank you.

**Comment by bmizes** [comment]
Thanks.  I closed the issue.

Barry

On Wed, Mar 26, 2014 at 1:19 PM, Philipp Andreas
notifications@github.comwrote:

> @bmizes https://github.com/bmizes Thanks again for your code changes. I
> just added the changes to the official documentation tips and tricks
> section http://docs.megapirateng.com/documentation/tipsntricks.
> 
> If i did not mess up transfering your changes please close this issue.
> Thank you.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MegaPirateNG/ardupilot-mpng/issues/106#issuecomment-38720390
> .

## 

Barry Mizes
7001 Washington Ave.
St. Louis, MO 63130

314-721-1841 voice
314-484-0504 cell

bmizes@yahoo.com
