### ISSUE TITLE
Gimbal is not working on Crius AIOP v2

### ISSUE THREAD

**Issue by KK159** [MegaPirateNG/ardupilot-mpng#109]
I tried to connect servos on Crius AIOP v2 to control camera gimbal, but servos are totally dead. 

In mission planner everything seems set OK.

Board is powered by separate BEC and loaded with MPNG 3.0.1 R4.

Does someone experiencing same problem?

**Comment by gio-loky** [comment]
In the Outputs pin 5v missing if you use a external bec, try to power the board through a bec on esc without external bec.
Sorry for my english ;)

**Comment by KK159** [comment]
Thx for the tip! 

For testing purpose I'll going to do that but and I'll report back result. Now I'm using 5A BEC and ESC BEC is 3A so I would like to use external BEC if possible somehow. 

Q: If I connect ESC power pin then I should remove BEC power + instal jumper or I can leave BEC power?

**Comment by gio-loky** [comment]
Remove external BEC. If you want use external BEC Connect +5v of servo to +5 of BEC like ie.
servo pin.  
signal   to crius
+5.       to external BEC
Gnd.    to crius

**Comment by KK159** [comment]
Seam you find solution for my problem :-). 

Now I'm going to rewire my setup in a way that I'll continue to power board with BEC and additionally I'll remove red wire (+) from gimbal servo and connect it directly to red wire (+) on 5V side of BEC. 
Tried this setup with improvised wiring and all worked OK.

Thx gio-loky!
