### ISSUE TITLE
Shutter on MPNG 3.0.1 R2

### ISSUE THREAD

**Issue by c-bob** [MegaPirateNG/ardupilot-mpng#11]
Can not find the possibility to get the shutter working. Is it not supported?

**Comment by negruli** [comment]
Hi C-bob something new to this topic? could you solve it?

**Comment by c-bob** [comment]
Sorry, have not much time these days, so I did nothing to find a solution :(

**Comment by SirAlex** [comment]
Which type of shutter you are interesting? Servo or Relay?

**Comment by negruli** [comment]
I dont know the type of shutter, i need to connect a Canon with chdk.
while work no matter the type of trigger, I would appreciate if you could guide me how to operate the trigger.

**Comment by SirAlex** [comment]
I'm don't know hot to interact with Canon too, so you must search internet for it.

Current MPNG 3.0.1 R3 firmware support only Relay type for Shutter. You must connect your shutter device into 46 pin of the Flight Controller. And select appropriate Shutter in Camera Gimbal settings in Mission Planner.

**Comment by negruli** [comment]
Thank you very much!

2013/10/24 Aleksey Kharlanov (Sir Alex) notifications@github.com
