### ISSUE TITLE
hk red multiwii pro well flashed with mpng plane 2.76 but no mavlink connection

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#110]
hello guys !

as explained, i've flashed my hk pro board with mpng 2.76
the firmware is compiled with ardupilot-arduino-1.0.3 patched with pde.jar
all the led's are blinking now
but i can't have a correct connection with APM-planner or mission-planner, nothing works, even in "terminal mode"  ( baud 115200, serial 6, that works perfecly for flashing)
I've tried to clear eeprom before and then re-flashing : nuts..

somebody can help me ?     :o)

**Comment by smurfy** [comment]
I guess you used my repo right? https://github.com/smurfy/ardupilot-mpng  
Did you also configured the correct board?

**Comment by nabakou** [comment]
hello Smurfy

thanks for answer

yes i've configured the right board (#define HK_RED_MULTIWII_PR0 in apm_config )but...
in fact i'm french speaker and maybe have i missed something in your explanations...    :o/

**Comment by smurfy** [comment]
Hm. ok, the error is a bit strange, you could try using the FlashTool to do the flashing if you use windows, just to make sure you configured everything correctly.

Other than that i'm currently out of ideas whats wrong.

**Comment by nabakou** [comment]
Do you mean Xperia flashtool ?

i have tried with arduplane 2.74 and with this version the mavlink works correctly but i can't change all the parameters for hk controller myself
with arducopter 27r4, all is ok too ( i use it for my hexacopter with the same hk controller)

  ----- Original Message -----

**Comment by smurfy** [comment]
http://docs.megapirateng.com/documentation/flashtool

**Comment by nabakou** [comment]
waw, this soft looks very interesting for people like me

unfortunately, i've tried several times with all good parameters and it is just pending "waiting for firmware" 

download works correctly for "apm copter quad" but not for "apm plane"

is there another way to upload firmware first, put it in "firmware" folder and then after it flash the card ?

**Comment by nabakou** [comment]
ok with 2.76, no more mavlink problems, thanks
