### ISSUE TITLE
trouble with Flashtool

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#111]
if You choose "apm_plane", there is a problem,  i've tried several times with all good parameters and it is just pending "waiting for firmware"

download works correctly for "apm copter quad" but not for "apm plane"

**Comment by smurfy** [comment]
Can you tell me what other parameter you are selecting?

It looks like a problem with the build server but by knowing your configuration i can help figuring out whats wrong.

**Comment by nabakou** [comment]
here it is   :o)

-hobbyking red multiwii
-regular pwm
-default
-apm-plane
-nmea 115200
-version 2.76
-com6

on windows xp...

**Comment by SirAlex** [comment]
@smurfy , @nabakou 
Looks like there is problem with BMP085 driver for HK Red board. Compilation fail if you choose board with BMP085.

**Comment by smurfy** [comment]
ok, i will take a look at my branch. thanks for the info

**Comment by nabakou** [comment]
ok, thank You

**Comment by smurfy** [comment]
Ok fixed, you should be able to flash 2.76

**Comment by nabakou** [comment]
wonderfull !
i was just trying arduplane 2x when receiving your message..
Now, 2.76 is well compiled, dowloaded and flashed, the card is working, no mavlink problems with terminal or apm planner
no more barometer problems
i'll try eagletree adressing later, because it's late here..
Thank You for the good job   ;o)

**Comment by smurfy** [comment]
no problem, if all works out, please close the issues. thanks

**Comment by nabakou** [comment]
ok, no more problems with Flashtool for me
