### ISSUE TITLE
mpng plane 2.74b well uploaded on red hk pro but eagletree i2c airspeed problem

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#112]
i can't always download 2.76 with Flashtool but 2.74b is ok
...but there is a conflict between BMP085 and eagletree i2c airspeed connected on pin 65
is there a solution ?
maybe 2.76 hasn't this problem...or can I do something (logicaly it is possible to work with several items connected on i2C)
..or must I buy an analog pitot like MPXV7002 ?

thank You  :o)

**Comment by smurfy** [comment]
what is the problem? does both devices use the same slave address?

**Comment by nabakou** [comment]
I think not, address for ealgletree is 0xEA and BMP 0x77 if i'm right
with mission planner, i've inserted PIN65 in the parameters as described for this module but when I verify with the terminal test function, it says something as "alert, problem on I2C bus with BMP085" with a beep

**Comment by nabakou** [comment]
the problem occurs even the eagletree module is not connected
with terminal connection the error message is : 
"panic : failed to take i2c semaphore 100 times in AP_baro_bmp085_mpng::_read_data_from_timerprocess"

**Comment by nabakou** [comment]
now, with 2.76 on the board, no more problem with barometer but airspeed eagletree module always don't works...
I've bought  an analog pitot but on the red hk board the A0 to A7 inputs are not connected to some headers.
With apm planner I've tried on A11 but the measure seems not good, it is maybe because in theory the A11 input must be connected  to an RC signal (the rudder i think)
Thus must I solder some wire on A0 or is there another solution ?

**Comment by smurfy** [comment]
not sure about A11 but in Missionplanner you are able to connect the airspeed to A0 to A9
But some Analog ports are reserved for other purpose i guess A11 too)

I only own a crius v2, there i can use A0 to A7. I guess you need to solder some headers on your board.they could be usefull if you want to connect for example a voltage sensor too.

**Comment by nabakou** [comment]
ok, i 'll try to solder all wires in one time, let say A0 for airspeed but on wich input must I connect the voltage sensor ?

**Comment by smurfy** [comment]
A1 and A2:

http://plane.ardupilot.com/wiki/common-using-a-current-sensor/

**Comment by nabakou** [comment]
ok, i'll try this operation...and let You know the results

**Comment by nabakou** [comment]
i have tried the operation :  it's just impossible for me to solder a wire only on one pin of the 2560...
thus i have short circuited A1/ A2 together ( i don't need current measure ) an A3/A4 for airspeed input, no problem these are all inputs
then airspeed and voltage measures are working well..
In Belgium we say in this case "oufti, ça marche"   :o)
Thanks for all

**Comment by smurfy** [comment]
ok, cool i thought you just need to solder the pins to already prepared holes.

But good work not frying your board :)
