### ISSUE TITLE
Missing Waypoints

### ISSUE THREAD

**Issue by bmizes** [MegaPirateNG/ardupilot-mpng#117]
I'm using 3.0.1R4 on a Crius 1.1 board with an external compass.  All my GPS modes tested out fine (altitude hold, Loiter and RTL) so I tried my first mission yesterday on an extremely calm day and it worked fine.  I tried it again today when it was much windier and the quadcopter started off in the general direction of the first waypoint but then just kept going, seemingly missing the waypoint but failing to detect that it had missed it.  What is supposed to happen when a waypoint is missed? 

 I tried it a second time, moving the first waypoint to a different spot and got the same result, i.e., moving off in the direction of the waypoint but going way beyond it.  In both cases, I had to switch to stabilize mode and bring it back manually.  Is this a software problem or just a problem with a setting?  In windier conditions, does one need to increasse or decrease the WPNAV_Radius parameter in the Full parameters screen and/or increase or decrease the WP Radius field at the top of the waypoints table in the Flight Plan Screen?  Or is there some other parameter I should be adjusting to help the copter determine that it has reached waypoint 1 and should change course to waypoint 2?  Thanks.

**Comment by smurfy** [comment]
I think this is a more general ardupilot question. You can try the APM official forum or the DIY Forums. I think there is some kind of radius thingy you can configure, but i'm not sure.

**Comment by bmizes** [comment]
Yep.  Adjusted the waypoint nav radius and now it works fine.
