### ISSUE TITLE
minim osd on red hk board connections

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#118]
hello one more time   :o)

is it right that i must connect minim osd on the same header than bluetooth module ?
...and then no possibilities to connect usb or bluetooth when osd is working..
Other question, the osd indicate his own battery voltage or the voltage connected to the board (A1) ?
Thanks

**Comment by smurfy** [comment]
> is it right that i must connect minim osd on the same header than bluetooth module ?

not sure what you have conntected to your board already, but you have two ports you can connect mavlink compatible devices (S0 and S3) and one GPS port. (S2)

The minimos needs to be connected to one of the mavlink ports.
Other devices like bluetooth, 3dr uses a mavlink port too.

Also Serial0 is shared with the onboard usb so it could cause problems if you want to flash your board and you have to disconnect the mavlink compatible device.

If you have nothing on S3 you can connect the minimOSD there or you connect it to S0 and have to remove the bluetooth.

> Other question, the osd indicate his own battery voltage or the voltage connected to the board (A1) 

Normally you can connect the voltage sensor either way. MinimOSD can display the voltage/current measured onboard or if provided via mavlink from the fc.

If you connect the sensor only on the minimOSD you can only see the data in your video feed. if you connect it to the fc you can see via telemetry like bluetooth or 3dr too.

You also could connect, if you use a separate battery for video, a second sensor for the video battery directly to the minimOSD and the main battery to the fc

**Comment by nabakou** [comment]
good new, thus I may connect it on S3 wich is free, much better !
Ok for the voltages, well understood
kind of You to waste time to answer me

**Comment by smurfy** [comment]
Nice setup you have, (only looked at the pictures, don't speak/read french). I don't own a car so its hard for me to have that much equipment. i drove with my bixler on my back and two bags on my bike to a friend sunday to do some flight testing :) 

I live in the city and need to get out to do tests.

**Comment by nabakou** [comment]
:o)     that's sport !
not easy to fly in towns, fortunately i live in the country
