### ISSUE TITLE
Support for MTK-3329 gps module

### ISSUE THREAD

**Issue by szakacs** [MegaPirateNG/ardupilot-mpng#12]
GPS: No GPS

Loaded ArduCopter-MPNG V3.0.1 R3b on HK_RED_MULTIWII_PRO.
# define MPNG_BOARD_TYPE   HK_RED_MULTIWII_PRO
# define SERIAL2_BAUD 115200
# define GPS_PROTOCOL GPS_PROTOCOL_NMEA

Is this the correct configuration for the above module ?

**Comment by ralphwu** [comment]
Did your board boot and the GREEN and BLUE LEDs light up?

**Comment by szakacs** [comment]
Yes the board boots up ..
The green and blue LEDs light up and stay steady.
In terminal - Test - gps I get      ..................................................
Most of the other functions seem to be working.
The MTK-3329 module has the v1.6 - AXN1.30_2389 firmware.
GPS works with previous versions 2.9.1b R8.158 and 2.8 R3
Is there anything else to test GPS function ?

**Comment by ralphwu** [comment]
You better update MTK GPS firmware to 1.9 for MPNG 3.0.1

The default GPS baud rate is 38400 except you change it to others using GPS configure software.

Loaded ArduCopter-MPNG V3.0.1 R3b on HK_RED_MULTIWII_PRO.

#define MPNG_BOARD_TYPE HK_RED_MULTIWII_PRO
#define SERIAL2_BAUD 38400
#define GPS_PROTOCOL GPS_PROTOCOL_MTK19

You can get the MTK firmware upgrade utility in www.ardupilot.com.

**Comment by ralphwu** [comment]
Can you share your APM_config.h file to me? It still hang. What did I do something wrong in compilation?

**Comment by szakacs** [comment]
Please find my APM_config.h attached.

GPS is still not working.

Hope this helps

**Comment by szakacs** [comment]
Still no joy ..

Updated firmware to 1.9. and tried your settings.

With MiniGPS tool I can verify that the firmware is AXN1.51_2776, but I see no output from the module.

The module outputs data with 1.6 firmware.

Is there a way to communicate with the module apart from MiniGPS to diagnose issues..i.e. using a terminal prog.

I have a feeling that the firmware is not working correctly, not compatible or I am missing some initialization procedure.

**Comment by ralphwu** [comment]
I compiled in Ubuntu 12.04 and the firmware did not work. Then I follow the official instructions and did it again on Windows 7 and worked. GPS also worked. Testing the hdop reading of GPS. But there is no reading of RC input.

**Comment by floboe** [comment]
I have the same problem on my HK_RED_MULTIWII_PRO:
With Version 2.9.1 beta the GPS module works with these settings:
#define SERIAL2_BAUD 115200
#define GPS_PROTOCOL GPS_PROTOCOL_NMEA

Since 3.0.1 R3 beta there is something wrong.

I followed the Howto:
http://www.megapirateng.com/compile-mpng-sources/

**Comment by ralphwu** [comment]
Battery voltage check fails and cannot arm the MulitWII Pro Board.

**Comment by mcknightly** [comment]
Hopefully this helps. I'm experiencing the same issue. I have the HK_RED_MULTIWII_PRO. I just loaded 3.0.1 r3b, and I cannot get the GPS working - using the same settings as above. GPS works with 2.x versions.

**Comment by SandroFly** [comment]
I too have the same problem. GPS with firmware 1.9 and HK_RED_MULTIWII_PRO.
if I install the old firmware in the GPS and configure GPS_PROTOCOL_NMEA on MPNG 3.0.1, 
working properly, but the data quality is not great...

I also have the problem "Battery voltage check fails"...
if I disable the "pre arm control" from mission planner, the system and mission planner ...freeze....

**Comment by szakacs** [comment]
Have managed to get it to work as long as the baud rate is set to 38400.
Tried 115200 with no joy.

Settings that are working are :

The MTK-3329 module has the v1.6 - AXN1.30_2389 firmware as the module will not accept v1.9

#define MPNG_BOARD_TYPE HK_RED_MULTIWII_PRO 
#define SERIAL2_BAUD 38400 
#define GPS_PROTOCOL GPS_PROTOCOL_MTK19

**Comment by SirAlex** [comment]
Looks like the #define SERIAL2_BAUD 38400  actually not works. It's may explain why 115200 GPS modules won't work.
I will check this.
