### ISSUE TITLE
Autotune in 3.0.1 R3 ?

### ISSUE THREAD

**Issue by Espenf** [MegaPirateNG/ardupilot-mpng#121]
Do you know if I can use autotune with
HK Multiwii and Megapirate AIO Flight Controller w/FTDI (ATmega 2560) V2.0 and MPNG 3.0.1 R3 ? 
This works on amp 2.5 with arducopter 2.8.1 by holding arm activated for about 20sek the you hover, keep it steady as you can for about 45sek and the tuning is written to the board.
Link to video: http://www.youtube.com/watch?v=FGiX-8m-6fw

**Comment by smurfy** [comment]
There are two different things. AutoTune is automatically configure the PID values of the copter. This feature is not present in 3.0.1 R3 (or R4 which you should use).

The YouTube video you linked showcasing AutoTrim not AutoTune.
AutoTrim should be supported by 3.0.1 R4

**Comment by Espenf** [comment]
Sorry for posting trim-video instead of tune. Anyway, tnx for letting me know that this feature is not available yet. Will it be in ver 3.1?
What are the changes from ver  3.0.1 R3  to R4 except concerning Paris board?  What will I gain by going to R4 now or is it feasible to wait for 3.1 ? :)

**Comment by smurfy** [comment]
R4 provides fixes for HKRED board, gimbal und paris board support.
3.1 is available in beta but i suggest sticking with R3 or R4.
Yes the 3.1 beta will support autotune.

**Comment by Espenf** [comment]
Tnx, Can you Please describe the fix for HKRED. I have both HKRED and HKBLUE.

**Comment by smurfy** [comment]
Based on @SirAlex commit message it fixes "bad Accel range". So something with the Accelerator.

If this resolves this issue, please close it. Thank you.
