### ISSUE TITLE
trouble with elevons mixing

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#124]
hello !
apng 2.76 on hk red board

it seems tha there is a problem in this mix
inputs are well ailerons and elevator but stabilisated outputs are rudder and elevator
unfortunately, this affect the mapping of gyros, bank and roll gyros are interverted
it can be resolved by an ahrs_orientation of 90 degrees giving but this make another trouble (see other post about horizon orientation in apm-planner)

**Comment by smurfy** [comment]
Possible related to #71

**Comment by nabakou** [comment]
hi Andreas   ;o)

yes, i've posted on this subject, my problem is the same

**Comment by smurfy** [comment]
Well i had a problem which could be related to this issue, not sure.

My friend flown his plane the first time, everytime he switched from manual to stabilize or something else, the plane goes nose down an almost crashes. (quick switch back to manual for saving the plane).

The problem was, that in the RC configuration in mission planner the "reversed" checkbox for pitch was not checked.

It seems that the RC configuration settings only affect the non manual modes.

Maybe you have the same problem?

Phil

**Comment by nabakou** [comment]
i think not because with servos connected on outputs rudder and elevator, all works correctly, elevons counteract well bank and roll and rc command are in the good way even in manual or stabilised or other mode
but...it's totally not logical that you must connect a servo on rudder output for a ailerons/elevator mixing
i think that there is a mismatch between elevon mix and Vtail mix in the software

**Comment by smurfy** [comment]
> rc command are in the good way even in manual or stabilised or other mode

if you hold you plane in your hands and move the plane in stabilize mode does it correct the ailerons and elevator correctly? Or is that inversed?

**Comment by nabakou** [comment]
yes,

the two elevons are well correcting bank and roll in all modes but i had to put ahrs-orientation on 90 degrees to intervert bank and roll action
thus : rc inputs are elevator and ailerons, servo outputs are rudder and elevator
ahrs_orientation is 90°
and the plane is ready to fly for all modes....elevons counteract perfectly bank and roll variations
but....in the right way, my servos would be connected to aileron and elevator outputs, and not rudder... that make me think that there is some mismatch in the programmated outputs in elevon mixing

**Comment by smurfy** [comment]
Hm, i think i don't completely understand the problem ^^

Maybe this helps: (the ELEVON_REV\* stuff)

http://plane.ardupilot.com/wiki/arduplane-setup/first-time-apm-setup/reversing-servos-and-setting-normalelevon-mode/

**Comment by nabakou** [comment]
:)   i'll try to be clear

in right way, if you do an elevon mix, RC inputs are elevator and ailerons and servos must be connected on elevator and ailerons outputs
for the moment, If you do that, just one servo is stabilised : the elevator, not the other....and just one rc command works : elevator
to have the 2 servos stabilised, you must connect these to elevator and rudder outputs...and then RC command are good (elevator and ailerons)
but, if you do that, a problem occurs : bank and roll stabilisation are interverted and in the same time if you move your stick right/left and up/down are good
to have good rc commands AND good bank/roll stabilisation , you must put ahrs_orientation on 90 °
unfortunately, this modification in orientation has a bad effect : in apm-planner and minim osd, the bank and roll interversion isn't corrected and the showed horizon is false, just as You look at left hand, when the plane turn right, your horizon goes to the ground in place of turning right

**Comment by icsss** [comment]
Does anyone successfully used apng 2.76 with elevons mixing?

**Comment by smurfy** [comment]
Ok, just to summarize my thoughts :)

The output config for non Elevon mixing planes like my bixler is:

| MPNG | APM | Channel |
| --- | --- | --- |
| D2 | 3 | Motor |
| D3 | 1 | Ailerons |
| D5 | 4 | Rudder |
| D6 | 2 | Elevator |

I figured out the MPNG Ports by simple testing them.

Based on @nabakou comment for elevon mixing i understand you need to connect it like this:

| MPNG | APM | Channel |
| --- | --- | --- |
| D2 | 3 | Motor |
| - | 1 | Ailerons    (Left Elevon) |
| D5 | - | (Left Elevon) Rudder |
| D6 | 2 | (Right Elevon) Elevator |

Did i get that? Right? So i can try to connect the outputs like this to my bixler enable elevon mixing and try to reproduce the problem.

Ok now what should happen and what does happen :) (movement  of the elevons if i move my sticks)

Also based on http://plane.ardupilot.com/wiki/arduplane-setup/first-time-apm-setup/reversing-servos-and-setting-normalelevon-mode/

Elevons can be setup in various ways :) Did you guys tested with: "New style elevon mixing EEPROM setup (ELEVON_OUTPUT option)" ?

**Comment by nabakou** [comment]
yes, connect servos on D5 and D6
radio on A9 and A11
elevons mixing = 1
elevons output = 0
elevons mix on radio is on
then sticks elevator and ailerons are moving the two servos , bank gyro stabilise in roll movement, roll gyro stabilise in bank movement

**Comment by smurfy** [comment]
Ok this suggests you are using the "old" method for elevon mixing :) I guess normally this should work too, but please try the new Style elevon mixing maybe this works better. :) 

I quoted the basics here:

#### New style elevon mixing EEPROM setup (ELEVON_OUTPUT option)

As of ArduPlane 2.73 there is a new ELEVON_OUTPUT option. This option allows you to setup your transmitter for normal aileron/elevator control and for ArduPlane to add elevon mixing on the output of channels 1 and 2. Using ELEVON_OUTPUT has a big advantage over ELEVON_MIXING that your inputs won’t saturate the roll/pitch control in FBWA mode, which means you can get better control of your plane.

The ELEVON_OUTPUT option is designed to operate exactly as a hardware elevon mixer would operate. To set it up follow these steps:
- Setup your transmitter with no elevon mixing
- Set both RC1_REV and RC2_REV to 1 and ELEVON_MIXING to 0
- Start by setting ELEVON_OUTPUT to 1. In later steps you may adjust this to 2, 3 or 4.
- Put your APM into FBWA mode
- Roll the plane to the right and observe what happens to the elevons
  - If the two elevons move in the same direction, then change ELEVON_OUTPUT to 2, and try again.
  - If the elevons move in opposite directions, but the APM is correcting the roll in the wrong direction (the left elevon is going down and the right one is going up) then change RC1_REV to -1
- Next try pitching your plane up. If the elevons move in the wrong direction then change RC2_REV to -1
- Now change to MANUAL mode and adjust your transmitter reversals for channels 1 and 2 to produce the right movement in MANUAL mode.

**Comment by icsss** [comment]
Does the  new ELEVON_OUTPUT work  with AIOP V1?

**Comment by smurfy** [comment]
> Does the new ELEVON_OUTPUT work with AIOP V1?
> I think it should work.

**Comment by nabakou** [comment]
ok, i'll try it and let you know..

**Comment by nabakou** [comment]
here are the results !
with this procedure : the gyros work well in bank and roll, the rc commands work well too ...
but, first problem : i must always connect one of the servos on the rudder output D5 in place of ailerons output D3 because if i connect something on D3 : the servo goes full range directly and don't move more
second problem :  the horizon displayed in apm-planner is inverted in roll, if I turn right, the horizon goes left, in bank there is no problem

there is a mismatch , i'm sure of that   :o)

**Comment by nabakou** [comment]
Hello Philipp,

ok, then all is correct
if You follow this procedure and connect servos on D5/D6, no more problems ( i don't know why you must use rudder output but it works )

i've made a mistake for apm-planner, all is right

thank You for all

**Comment by smurfy** [comment]
Ok cool, about the D5/D6 thing, i think you should not think about Rudder or Aileron Output but of Elevon Output :)

Ok, i want to update the Documentation as-well.

Is D5 the left Elevon and D6 the right Elevon or the other way around?
Also the the Input config of your RC is the same as for the non ELEVON config right?
You also don't need the "ahrs_orientation" correct?

I will update the documentation over the next couple of days and appreciate if you can have a look afterwards if everything is correct.

> i've made a mistake for apm-planner, all is right

yepp, that confused me a bit in comparison with multiwii. but based on some research apm does it the correct way. plane rolls right, horizon moves to the left. :D

**Comment by nabakou** [comment]
ok, let's go   :oP

connections : 
motor : D2
right wing : D5
left wing : D6
radio throttle : A10
radio ailerons : A9
radio elevator : A11

parameters :
elevons output : 3
elevons mixing : 0
RC2_rev : -1
ahrs orientation : 0
compass orientation : 2

radio  : 
elevon mixing : none
ailerons command : reversed
elevator command : normal

**Comment by smurfy** [comment]
Ok, just updated the docu: 
http://docs.megapirateng.com/documentation/connecting_components_plane

Are you sure about the radio connections with the board? because its swapped with the "normal" plane's ones :)

**Comment by nabakou** [comment]
yes, it'a surprise (one more) but it's right
i've verified for the 10th time all in manual mode and stabilised modes, elevons go in the right direction with radio and gyros
i just have a problem for accelerometer calibration "calibration failed" each time, i suppose that my positions right/left/up/down are not so accurate

**Comment by nabakou** [comment]
hi Smurfy,

confirmation : i've tried this yesterday at the field, all works fine : manual and fbwb modes

yepeee !   :o)

now, i have to try RTL, loiter ...next step

**Comment by smurfy** [comment]
cool, i'm glad everything is working as intended.

I need to fix my bixler :), somehow mine won't fly, (not a mpng problem) but luckily i can test with another one

**Comment by icsss** [comment]
My flying wing setup works flawless. 
I have tested: FBWA, FBWB and LOITER.
Thanks!

**Comment by smurfy** [comment]
icsss, cool to have a second confirmation, thanks

**Comment by nabakou** [comment]
good luck for your Bixler !  
  ;oP
