### ISSUE TITLE
COM port not detected in Flashtool

### ISSUE THREAD

**Issue by leocopter** [MegaPirateNG/ardupilot-mpng#126]
I'm trying to use Flashtool 1_0rc2. It is not detecting my COM port. I tried reassigning the COM port to a lower number. No go. I tried another HK AIOP board = no detection. Any idea of what's going on ?
(I can upload via Arduino and connect to Mission Planner, no problem).

**Comment by smurfy** [comment]
please close this ticket, its a duplicate of the one at the flashtool repro
