### ISSUE TITLE
arduplane 2.76 : some "manual mode" trouble ?

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#130]
hello there,

i've tried my arduplane yesterday with only one flight
manual take off ok,
loiter test ok, 
rtl test ok, 
waypoints test ok but just one time, when i ask a second time the same travel he don't wants to do
after that fbwb flight : ok

..and then, i come back to manual mode...and the plane becomes totaly crazy and crashes !

some idea for me ?

**Comment by icsss** [comment]
Have you eliminated mechanical or servos problems?

**Comment by nabakou** [comment]
yes,

no problems in this way...

with my hexacopter, i have a similar problem : when i change mode from automatic to loiter, all engines stop, the hexa loose 3 or 4 meters vertically and then motors come back running

i think that the problem is similar but the failure reactions are different for a plane..

**Comment by icsss** [comment]
What you have described for copter, looks like a vibration or baro problem.
Probably not our concern here since you mentioned that it happened in manual mode and arduplane is less sensible.

Have you done any successful flights in normal mode before that?

**Comment by nabakou** [comment]
yes i've made the first flight in manual and fbwb modes without problems , before that the plane has a lot of flights done without arduplane installed (it's a skyfun)

the problem occurs in the second flight

**Comment by icsss** [comment]
I'm out of ideas..
I ask you again.. have you checked if all the servos are working after the crash? BEC voltage? Servo linkage? How low was your lipo voltage when crashed?
Manual mode should be last resort when AP goes crazy..

**Comment by nabakou** [comment]
i'm not sure that manual mode is so safe because i've a friend who has the same problem
his Bixler has crashed 4 times, at each times he can't take the manual control of the plane to evitate the crash...and after the crash, all seems ok for lipo, servos ...
..don't know

**Comment by nabakou** [comment]
ok,

i've made a new plane with some new details : separate battery for receiver and ardu-board, CG little bit less rear to be secure about stalls, and now it flies very well...don't know the reason of the first crash for the moment...
