### ISSUE TITLE
patch for RSSI input in v3.0.1R4 on Crius AIO

### ISSUE THREAD

**Issue by thomasbutler** [MegaPirateNG/ardupilot-mpng#131]
I realize you folks are not making any more changes to v3.0.1R4, so here is a patch for those who might be interested.
RSSI pin value is not implemented which causes MissionPlanner to not be able to enable a pin for RSSI input.  Note uses pin A0 which is normally for sonar.
Patched code with:
In config.h, line 218, insert "#define RECEIVER_RSSI_PIN 0" after the battery current pin define.
In parameters.ino for the RSSI object, line 193 change "-1" to RECEIVER_RSSI_PIN which allows pin to be settable in MissionPlanner.

Go to MissionPlanner and enable RSSI_PIN.  RSSI will now be sent via MavLink to MinimOSD.  Note MinimOSD must be enabled and the range set to to display the RSSI.
Test with a 1.5v battery connected to A0 or use your battery monitor input from the AttoPilot; should show about 100% (depends on charge in battery) and test with A0 connected to ground; should show 0%.

**Comment by smurfy** [comment]
Thanks, i just added your tip to the tipsntricks section of the documentation:

http://docs.megapirateng.com/documentation/tipsntricks

**Comment by smurfy** [comment]
@thomasbutler Can you please close this issue?, thank you
