### ISSUE TITLE
ArduplaneNG 2.76 won't upload

### ISSUE THREAD

**Issue by mastercrash** [MegaPirateNG/ardupilot-mpng#134]
If I try to upload up to date, just downloaded version of MegaPirateNG - APM:Plane 2.76, I get this error at the end : 
avrdude: verification error, first mismatch at byte 0x3c000
         0x2a != 0x00
avrdude: verification error; content mismatch

But if I use a 2.76 version downloaded few months ago it works without any problem.

I use jar.pde and libraries from the corresponding repo...
What has changed ?
Thanks

**Comment by SirAlex** [comment]
This error means you are got too big HEX file. It cannot fit into AVR EEPROM.
You must disable some features to reduce FW size.

**Comment by mastercrash** [comment]
Too big, even if the compilation result is : 
Binary sketch size: 245 886 bytes (of a 258 048 byte maximum)

It seems there is still free space.

What kind of feature can be disabled? 
I just need to comment some lines or delete them completely?

**Comment by SirAlex** [comment]
FW cannot be  bigger than 245760 bytes (0x3c000). Because at this address begin protected area of Bootloader.

You may disable CLI for example. Or Logging

**Comment by mastercrash** [comment]
Good to know
Thanks a lot
