### ISSUE TITLE
HK_RED_MULTIWII_PRO BOARD DON'T BOOT IN 3.0.1 R3 Beta

### ISSUE THREAD

**Issue by ralphwu** [MegaPirateNG/ardupilot-mpng#14]
I successfully compiled and uploaded 3.0.1 R3 on HK_RED_MULTIWII_PRO, but it does not boot and no response on LEDs (GREEN, BLUE, RED).

**Comment by SirAlex** [comment]
Show your APM_Config.h, looks like you actually selected other board.

**Comment by ralphwu** [comment]
// -_\- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -_-

// User specific config file.  Any items listed in config.h can be overridden here.

// Select Megapirate board type:
#define MPNG_BOARD_TYPE   HK_RED_MULTIWII_PRO
/*
  RCTIMER_CRIUS_V2    -- (DEFAULT!!!) Use ONLY for RCTimer CRIUS V2 board
  CRIUS_V1            -- Use this define for RCTimer CRIUS V1(1.1) board and all HobbyKing AIOP boards
  HK_RED_MULTIWII_PRO -- HobbyKing MultiWii Pro board with ITG3205 and BMA180, BMP085 sensors
  BLACK_VORTEX
 */

// Currently not supported
#define CONFIG_SONAR DISABLED

//#define COPTER_LEDS DISABLED 

// GPS port speed (Serial2) 38400 by default
#define SERIAL2_BAUD 38400

// GPS driver selection
#define GPS_PROTOCOL GPS_PROTOCOL_UBLOX

**Comment by ralphwu** [comment]
SirAlex,

Firmware compiled in windows following your instruction worked. 

I did not work in Ubuntu 12.04.

**Comment by SirAlex** [comment]
How you compile it under Ubuntu? Are u using 'make' or what?

**Comment by ralphwu** [comment]
Just the old way, copy the library to replace the library in arduino folder and replace pde,jar to lib folder. However, the RC inputs show nothing.

**Comment by SirAlex** [comment]
This is separate: issue #16 and it now closed.
