### ISSUE TITLE
Datalog memory for CRIUS AIO V1 board - external memory

### ISSUE THREAD

**Issue by greenmen88** [MegaPirateNG/ardupilot-mpng#148]
Hi,

I want to have datalog capability in Crius V1 board (from HobbyKing). I prepare board with AT45DB161D external memory flash following tutorial under this link -> http://www.devfor8.com/datalog/

There is written I must use ISP pinouts to connect to SPI main line. But tutorial is written for version 2.9 and I use newer version - 3.0.1r4. These versions differs in dataflash code for datalogging. I cant find file "DataFlash_CRIUS_AIOP2.cpp" or any functions which communicate with flash memory so I can change pins corresponding for communication.

And here is my question: Where can I find those part of code? Or even how to change this?

Thanks in advance.

**Comment by smurfy** [comment]
The mpng adaption of 2.9 and 3.0.1 is completely different.
So the author of the data logger need to update his code or somebody else who is interested.

**Comment by SirAlex** [comment]
@greenmen88 
You can connect flash memory like described in http://www.devfor8.com/datalog/
Except:
1. Do not modify DataFlash_CRIUS_AIOP2.cpp file. 
2. Change ChipSelect(SlaveSelect) pin in file **libraries\AP_HAL_MPNG\SPIDeviceManager_MPNG.cpp**
AVRDigitalSource\* df_cs = new AVRDigitalSource(**_BV(0), PB**);
PB - is ATMEGA port
_BV(0) - pin in this port

**Comment by greenmen88** [comment]
Ok, thank You guys for answers! 
So only to clarify:
1. I connect prepared prototype board with external flash to Crius V1 ISP pins.
2. Change Slave Select to any unused pin (in line which SirAlex specified).
3. Change MPNG_BOARD_TYPE to RCTIMER_CRIUS_V2.
And thats all? GREAT.

I will try that this weekend and post results here. 
Thank You again for help.

**Comment by DevFor8** [comment]
I just tested it and something is wrong but I am not sure what 

Board is HK Crius v.1 clone
CS pin is 33 on board (old code is #define DF_SLAVESELECT 33)
So it should be PC4 on ATMega2560 and I used
    AVRDigitalSource\* df_cs = new AVRDigitalSource(_BV(4), PC);
but it doesn't work, hang on start :-(

SirAlex, can you help me ? I am checking what I can but I don't see anything wrong :-((

**Comment by DevFor8** [comment]
It looks that I found it. At least DataFlash_test work now. I am finishing solution and will publish it soon

**Comment by DevFor8** [comment]
So changes are covered here http://www.devfor8.com/datalog_3/ . It is issue recommended by SirAlex but there is also one more change. SS pin (standard one, not selected CS) have to be put on OUTPUT because it is required by ATMega (see Master Mode in 2560 datasheet, page 200)

**Comment by greenmen88** [comment]
Today I tested everything out. I'm glad to say that IT WORKS flawlessy! 

Thank You for Your help especially SirAlex for writing whole MPNG and DevFor8 for making this mod.

Issue  solved. I'm closing topic.
Cheers
