### ISSUE TITLE
download/display dataflash log with terminal not possible

### ISSUE THREAD

**Issue by sitoca** [MegaPirateNG/ardupilot-mpng#15]
Id like to display the vibrations of my quad. Set the Log bitmask to Default+IMU in Advanced Params screen and went to fly. After flight i tried to download my log with terminal. The log screen shows:
?
Commands:
  logs
  setup
  test
  reboot
  help
ArduCopter-MPNG V3.0.1 R2] logs
ArduCopter-MPNG V3.0.1 R2] exit
ArduCopter-MPNG V3.0.1 R2] logs
ArduCopter-MPNG V3.0.1 R2] 

I cant choose anything at "download these logs"
Using  Mission Planner 1.2.81 
          Crius AIO V2
          MPNG V3.0.1 R2

Is there something i did wrong?
Do I have to enable something like a global logging?

Thanks!

**Comment by SirAlex** [comment]
This may happen, if you disabled Logging in APM_Config.h

**Comment by sitoca** [comment]
Thank you! That was my problem!  Logging is Working now!
