### ISSUE TITLE
artificial horizon inverted on Minim OSD

### ISSUE THREAD

**Issue by nabakou** [MegaPirateNG/ardupilot-mpng#150]
hello guys !

my Skyfun arduplane 2.76  on HK red board flies very well : all flights modes ok
I've done let's say 15 flights with some in FPV and i'm very happy

now with minim OSD connected, all works but artificial horizon is inverted on the screen, when i turn left, horizon goes right      :o°

there is a parameter  in configh ( define pitch invert )  for this purpose but i don't have access to configh because i've used a precompiled version of arduplane 2.76 uploaded with flashtool.
I've done that because a lot of problem to compile it with arduino...nearby impossible for me

Is there some solution ?

thanks

**Comment by smurfy** [comment]
Please create a ticket @ the flashtool repro with the exact config you like to set and i will update the flashtool with said option.

**Comment by nabakou** [comment]
hello Philipp,

always a quick service with You, Thank You   ;o)

sorry but i don't exactly what You mean with "a ticket @ the flashtool repro "

i have a Red board multiwii pro HK, regular pwm A8-A15, graupner/spektrum, apm plane, NMEA, 115200, 2,76 

is that the good answer ?

**Comment by SirAlex** [comment]
Maybe I wrong, but:
'In an artificial horizon, when the aircraft tilts to the right, the horizon tilts to the left. (Just tilt your head and you can visualize this). This is normal! Please don’t tell us it’s reversed ;-)'
(From APM wiki)

**Comment by nabakou** [comment]
ooooooops....mayday mayday....I become totally stupid   

of course You're right....and I go to sleep, main processor is overloaded !

sorry for this mistake and thank You for all      ;o)

**Comment by smurfy** [comment]
great :) i was about to write the same thing as siralex, but thought you are aware of how the horizon works :)

ps. after i used mpng for the first time, i too was confused at first, because its different than multiwii.
