### ISSUE TITLE
No RC Input in 3.0.1 R3 Beta 

### ISSUE THREAD

**Issue by ralphwu** [MegaPirateNG/ardupilot-mpng#16]
The Min/Max values of radio are 0 and 3000, also there is no RC radio input detected. No way can do RC Radio Calibration.

I am using HK_RED_MULTIWII_PRO

**Comment by floboe** [comment]
The RC-Radio works well on my HK_RED_MULTIWII_PRO
I changed the follwing entries to use regular PWM inputs A8-A15:
libraries\AP_HAL_MPNG\RCInput_MPNG.cpp:
#define SERIAL_PPM SERIAL_PPM_DISABLED
// Multiwii
// ROLL,THROTTLE,PITCH,YAW,AUX1,AUX2,CAMPITCH,CAMROLL
static uint8_t pinRcChannel[8] = {1, 2, 0, 3, 4, 5, 6, 7};

**Comment by smurfy** [comment]
as @floboe alread posted this is not really a bug.

Its also discribed here: http://www.megapirateng.com/how-to-configure-mpng-3-0-1-firmware/

But i would suggest moving the configuration where it belongs (`APM_Config.h`)

**Comment by ralphwu** [comment]
Problem solved! Thks
