### ISSUE TITLE
Bluetooth MegaPirateNG 3.1.5-R2 Problem

### ISSUE THREAD

**Issue by nunofmds** [MegaPirateNG/ardupilot-mpng#161]
Hi, I'm testing the MegaPirateNG 3.1.5-R2 and i'm having issues with bluetooth and droidplaner for example...On version MegaPirateNG 3.0.1 R4 works fine so I think something is wrong on this new version...

**Comment by nunofmds** [comment]
I just start reading the code and figure out what's necessary to put bluetooth working like the 3.0 version...

FILE: Parameters.h    -> SEARCH FOR: serial1_baud, k_param_gcs1, k_param_serial1_baud REPLACE: serial3_baud, k_param_gcs3, k_param_serial3_baud
FILE: Parameters.ino  -> SEARCH FOR: SERIAL1_BAUD                                     REPLACE: SERIAL3_BAUD 
FILE: Parameters.ino  -> SEARCH FOR: gcs[1],  gcs1,       "SR1_"                      REPLACE: gcs[3],  gcs3,       "SR3_"
FILE: System.ino      -> SERACH FOR: SERIAL1                                          REPLACE: SERIAL3
FILE: GCS_Mavlink.ino -> SERACH FOR: SERIAL1                                          REPLACE: SERIAL3

**Comment by marlb64** [comment]
Hi Look here I had the same trouble

https://github.com/MegaPirateNG/ardupilot-mpng/issues/149

Grtz

**Comment by nunofmds** [comment]
Yep, confirmed...Just 

#define SERIAL1_BAUD      115200                     // Bluetooth port speed (Serial3) 
#define SERIAL2_BAUD      115200                     // GPS port speed (Serial2) 38400 by default
#define SERIAL3_BAUD      115200                     // Bluetooth port speed (Serial3)
