### ISSUE TITLE
Autotune in ver 3.1.5 R2

### ISSUE THREAD

**Issue by Espenf** [MegaPirateNG/ardupilot-mpng#163]
Guess I will test the autotune after a while.. Is this supposed to work like described here ?
http://copter.ardupilot.com/wiki/autotune/

**Comment by SirAlex** [comment]
Yes, it must work like described

**Comment by Espenf** [comment]
Tnx Aleksey..i look forward to improve PID settings without spending hours on testing. I would also like to thank you for all your work done so far on the MPNG code and also answer questions. Tnx a lot!!
