### ISSUE TITLE
Loiter turns does not maintain altitude

### ISSUE THREAD

**Issue by lion13ch** [MegaPirateNG/ardupilot-mpng#17]
CRIUS AIOP 1.1. MPNG 3.0.1 R2.
Loiter and AltHold turns does not maintain altitude.

It'is known bug in AC 3.0.1. How can I fix It at MPNG ?

**Comment by SirAlex** [comment]
Wait for MPNG 3.1 it will be available as soon as ArduCopter 3.1 will be released.

**Comment by lion13ch** [comment]
Здравствуйте, Алексей!

Я правильно понимаю, что проблема с некорректной стабилизацией высоты при
поворотах в режимах Alt Hold и Loiter - общая проблема для версии 3.0.1 ? Или это
только у меня так ?

Квадролет просто то "падает", то поднимается при вращении коптера. В реживах
Stabilize и Acro такого не наблюдается.

Леонид Чередниченко.

  14 Октябрь 2013 г. 11:14:37 пользователь Aleksey Kharlanov (Sir Alex)
  (notifications@github.com) написал:

  Wait for MPNG 3.1 it will be available as soon as ArduCopter 3.1 will be
  released.

**Comment by lion13ch** [comment]
Problem is fixed. 2 of 4 propellers had defects. But why it  makes such effect and only at althold and loiter mode - is another question.
