### ISSUE TITLE
TBS Discovery / DeadCat Frame Setup for MPNG 3.1.5 (Not a issue but a question)

### ISSUE THREAD

**Issue by CrashDBN** [MegaPirateNG/ardupilot-mpng#171]
Hi there Guys

Ok so here is the question. On previous version of MPNG I was lead to believe you could only set the frame type in the sketch and there is only the + X frame types. Now I understand that when setting up the Deadcat or TBS Discovery frame you need to set this a V type frame, but when using both the new flash tool and sketch I don't see the option for a Quad V Type in the options.

Sooo can you now select your frame type within Mission planner or is that still not a option for us Megapirate guys.

Thanks

**Comment by thatjoshguy** [comment]
I've always chosen the V type frame in MP and haven't had an issue.

**Comment by CrashDBN** [comment]
Hey there Thatjoshguy. Thanks for that. I've done that but I've noticed if I put the quad into a full yaw spin. When I stop the spin the back two motors spin up more/faster than the front ones causing the quad to lurched forward. Nothing serious just something I've noticed.
