### ISSUE TITLE
Accelerometer failing calibration

### ISSUE THREAD

**Issue by bigjake** [MegaPirateNG/ardupilot-mpng#18]
AIOP V2 with 3.0.1 R2. Accel calibration keeps failing. Artificial horizon moves normally on data screen.

Thank you.

**Comment by edw00d4711** [comment]
Please try it via console:
setup
accel

Any errors?

**Comment by bigjake** [comment]
Terminal shows this after going through accel setup:
Offset -3.14, 0.64 0.06
Scaling 1.00 1.00 1.00
Failed
INS
G_off -0.03 -0.08 0.01
A_off -2.99 0.58 0.52
A_scale 1.02 0.97 0.99

Thank you for the help.

**Comment by edw00d4711** [comment]
Edit the file with notepad (best notepad++)
AP_InertialSensor.cpp

line 421

if( accel_offsets.is_nan() || fabs(accel_offsets.x) > 2.0 || fabs(accel_offsets.y) > 2.0 || fabs(accel_offsets.z) > 3.0 ) 

to match your settings.

**Comment by bigjake** [comment]
Changes made.  Reflashed firmware.  Accel calibration still fails.  In terminal, states when doing through setup:

initinalising gyros
MPU6000:unable to get semaphore

Then the cursor sits.

The accel works on the data screen, just not calibrated.

Thank you for help.

**Comment by bigjake** [comment]
I replaced this line:

if( accel_offsets.is_nan() || fabsf(accel_offsets.x) > 3.0f || fabsf(accel_offsets.y) > 3.0f || fabsf(accel_offsets.z) > 3.0f )

With this line:

if( accel_offsets.is_nan() || fabs(accel_offsets.x) > 2.0 || fabs(accel_offsets.y) > 2.0 || fabs(accel_offsets.z) > 3.0 )

Is that correct?  I see the values have changed to 2.0, 2.0 but also the f's are gone as well from the code line.

I did not eliminate the f's when tested.  Is that important?

Thank you.

**Comment by edw00d4711** [comment]
Please, post here this information:
1. MPNG version:
2. Board type (RCT Crius v1,v2, HK... etc):
3. ESC type
4. RC Receiver type and how you connected it to board (PPMSUM, PWM):
5. How you power board(ESC, BEC...):
6. What also you connected to board (OSD, modem...)
7. If any logs(I'm prefer from board if available), video available, please post it here:

**Comment by bigjake** [comment]
MPNG 3.0.1R2
RCT AIOP V2
HK mystery 25amp ESC
Receiver FrSKY D6FR cone tied A8-a15 individually
Power by UBEC
Aso, GPS(UBEC ), 3DR radio
No logs or video.  Can't get it to fly without the accel calibration.

Thank you very much for your effort.
Jake

**Comment by edw00d4711** [comment]
Does console -> setup -> level work for you?

**Comment by bigjake** [comment]
Seem to do so.

Results:

G_off -0.03, -0.08, 0.01
A_off -3.20, 0.46, 0.05
A_scale 1.00, 1.00, 1.00

Retried the setup accel after that but failed again.

Thank you

**Comment by sosko71** [comment]
change line 421 

if( accel_offsets.is_nan() || fabs(accel_offsets.x) > 3.5 || fabs(accel_offsets.y) > 3.5 || fabs(accel_offsets.z) > 3.5 )

its work for me

**Comment by bigjake** [comment]
That did the trick.  Thanks for all the help.

Jake.
