### ISSUE TITLE
Cannot Calibrate Compass

### ISSUE THREAD

**Issue by pcace** [MegaPirateNG/ardupilot-mpng#190]
Hi,

i am using Megapirate 3.0.1 R4 (Installed via Flashtool). When trying to connect to the Cirus AIO (Hbbyking) i can do this, but whenever i want to arm the machine i get: "PreArm Compass not calibrated". 

I calibrated the Compass via GUI and via Terminal, i also did setup erase and setup reset.

I tried variouse settings: Cirus AIO V1 and V2, I Also tried 3.1.5-v2 / same Problem. 

How can i solve that issue?! Anz help would be just amazing!

Thank you so much!

**Comment by Espenf** [comment]
You should be able to use the guided setup from MP. Calibration dance video and look this topics maybe. http://copter.ardupilot.com/wiki/prearm_safety_check/

**Comment by Espenf** [comment]
I am using 3.1.5 R2, Blue AIO from HK
![18-12-2014 22-40-00](https://cloud.githubusercontent.com/assets/6025845/5496438/6fde4ff2-8707-11e4-90ac-954fc3214ee6.jpg)

**Comment by Espenf** [comment]
Guess its not wise to update firmware..

**Comment by ygoroak** [comment]
I had this issue and solved it by setting the parameter COMPASS_LEARN to "enabled".

**Comment by dawnhero** [comment]
I have same problem AND solved.
It just arm check problem.
You have to skip GPS check. because HK FC is not have GPS
