### ISSUE TITLE
Loiter Fly Away Problem with MPNG 3.1.5 R2

### ISSUE THREAD

**Issue by StenUhlig** [MegaPirateNG/ardupilot-mpng#194]
Hi,

I run a CRIUS AIO V2 and NEO 6 with MPNG 3.1.5 R2.

Vibrations are Ok (I use an anti vibration mount). I run the GPS on UBLOX. 
I did  AutoTrim and AutoTuning successfully. 

The copter (quad) flies good in stabilize and in alt_hold!

As soon as I switch to Loiter, the copter flies away in random(?) directions.

Analyzing my logs did not help so far. 
hdop is below 2. 8-11 sats.

AutoAnalyzer says:
Test: Compass = GOOD - mag_field interference within limits (20.43%)
Test: GPS = GOOD - 

and so on.

What is wrong? Any idea? 

Thanks!!

**Comment by ther0x** [comment]
My friend give me a second GPS (the same model) and I have to make some test
I left the original GPS setup

Let you know

**Comment by ther0x** [comment]
Do you have made autotrim?

**Comment by StenUhlig** [comment]
Yes, i did. But this did not help.

After flushing my FC and reinstalling MPNG 3.1.5 using the flash tool - loiter is working now!

**Comment by ther0x** [comment]
sorry but how do you have flushed your FC? from mission planner?

**Comment by StenUhlig** [comment]
no, i did an EEPROMClear using arduino (http://arduino.cc/en/Tutorial/EEPROMClear) and reinstalled MPNG with the flash tool!

**Comment by ar99** [comment]
EEPROM clear is the same that cli command setup -> erase?

**Comment by StenUhlig** [comment]
I don't know!

**Comment by SirAlex** [comment]
Yes, it's same operation.
11 февр. 2015 г. 2:41 пользователь "ar99" notifications@github.com
написал:
