### ISSUE TITLE
No Radio Connection

### ISSUE THREAD

**Issue by thorphar** [MegaPirateNG/ardupilot-mpng#20]
Just to start off with Please Help. Right, I have installed the firmware on to the Crius board via the instruction on the megapirateng.com page of how tos. I managed to get every thing correctly configured and when i got to the radio config section none of my radio inputs were displayed on the mission planner software. If you need any photos of my set-up just let me know.  

Thank You 

"If Linux doesn't have the solution, you have the wrong problem"

More jokes to come every time someone gets me that closer to joining the copter society

**Comment by claytonc2001** [comment]
Are you using PPM? If not follow step 3 of setup.
1. Changing RC input type to regular PWM inputs A8-A15

Important! By default, Serial PPM on A8 pin selected

To disable Serial PPM signal processing, and use separate input pin (A8-A15) for each RC channel. Open file ardupilot-mpng\libraries\AP_HAL_MPNG\RCInput_MPNG.cpp
Replace this line:

1 #define SERIAL_PPM SERIAL_PPM_ENABLED 

With this:

1 #define SERIAL_PPM SERIAL_PPM_DISABLED

**Comment by thorphar** [comment]
Oh My god thank you thank you. I could not find that information anywhere.

**Comment by smurfy** [comment]
@SirAlex as suggested before in a similar ticket, why not move this configuration to `APM_Config.h` instead of the need changing something in the library.

**Comment by thorphar** [comment]
I know it is not related to this issue but as you have been so helpful. Is it possible to change the config to allow the crius board to be mounted to a frame in a + config and then modify the config to make it think it is in a x config

**Comment by SirAlex** [comment]
@smurfy  APM_Config.h not visible in RCInput, :)

**Comment by smurfy** [comment]
> @smurfy APM_Config.h not visible in RCInput, :)

hm, so i guess, exposing the settings via parameters is also not possible without changeing to much?

**Comment by Kmonk** [comment]
Hi everyone,

I'm having the same issues with no radio connection, where do I find "1 #define SERIAL_PPM SERIAL_PPM_ENABLED" to disable it?

**Comment by smurfy** [comment]
look at the previous comments

> Are you using PPM? If not follow step 3 of setup.
> 
> ```
> Changing RC input type to regular PWM inputs A8-A15
> ```
> 
> Important! By default, Serial PPM on A8 pin selected
> 
> To disable Serial PPM signal processing, and use separate input pin (A8-A15) for each RC channel. Open file ardupilot-mpng\libraries\AP_HAL_MPNG\RCInput_MPNG.cpp
> Replace this line:
> 
> 1 #define SERIAL_PPM SERIAL_PPM_ENABLED
> 
> With this:
> 
> 1 #define SERIAL_PPM SERIAL_PPM_DISABLED

**Comment by Kmonk** [comment]
I did, it's how to find "1 #define SERIAL_PPM SERIAL_PPM_ENABLED" to that's the problem:)

**Comment by smurfy** [comment]
>  Open file `ardupilot-mpng\libraries\AP_HAL_MPNG\RCInput_MPNG.cpp`

its around line 17 you also could use ctrl + f to search in the aruino software to search for the old value

**Comment by Kmonk** [comment]
I'm using a HK V2 AIO pro board, with "ArduCopter-MPNG V3.0.1 R2"

**Comment by Kmonk** [comment]
I'm a total newbee, this is the first time I've tried this.

**Comment by Kmonk** [comment]
"its around line 17 you also could use ctrl + f to search in the aruino software to search for the old value"

You completely lost me here smurfy, around line 17 where, and in what?

**Comment by edw00d4711** [comment]
Please read http://www.megapirateng.com/how-to-configure-mpng-3-0-1-firmware/ Point 2.

**Comment by Kmonk** [comment]
Thanks guys, finally figured out how to do it, was looking in the H file instead of the CCP one!
