### ISSUE TITLE
Startup Problem

### ISSUE THREAD

**Issue by thorphar** [MegaPirateNG/ardupilot-mpng#21]
I have wired in my motors after configuring my radio through mission planner, but nothing is happening. My motors beep for a bit then stop.

**Comment by smurfy** [comment]
i'm also having motor problems but i still use incorrect wiring. (migrating from multiwii)

But i had the problem that after arming the board the motors still did not spin after giving some throttle.
My problem was that the THR_MIN value was too low so the esc's did not arm.

Try increase the value and or try giving full/more throttle and see what happens.

I use a X8 config so i'm a bit special i guess but i got my motors to spin with quad X config. (X8 config not so much. only 3 motors spin :), but it needs some work on my part)

**Comment by edw00d4711** [comment]
ESC calibration done?
https://code.google.com/p/arducopter/wiki/AC2_ESC

**Comment by smurfy** [comment]
> ESC calibration done?
> Thanks after calibration the motors mostly work. (6 of 8 spin :D)

**Comment by edw00d4711** [comment]
Problem fixed?
Can you close the thread?
