### ISSUE TITLE
Crius v1.0 and v1.1 only have pins A0-A5. Use the pin 35 for ARMED external LED

### ISSUE THREAD

**Issue by thomasbutler** [MegaPirateNG/ardupilot-mpng#22]
I know Alex or someone is working on a fix for the LEDs, but here is a temp fix I've used since 2.8r2.  Added it to 3.0.1r2 and it works OK. 

Crius v1.0 and v1.1 only have pins A0-A5. These boards have pins 34 and 35 available.
Note the Crius v2.0 was corrected and has A0-A7, and the pins 34 and 35 have no
connector; just a solder pad.

This fix will use the pin 35 for connection of external LEDs to indicate the copter is
armed.

Modifies:
  ArduCopter.ion
  Config.h
  Leds.ino
  Motors.ino
  System.ino

 tb patches and config changes

 For external LEDs,
 in config.h
  # define A_LED_PIN        13
  # define B_LED_PIN        31
  # define C_LED_PIN        30
//tb 10/19/2013 use pin 35 on Crius for external status pin A
  # define A_LED_PIN_EXTERNAL 35

 in leds.ino
         // set arming led from arming_light flag
        if(ap_system.arming_light) {
            digitalWrite(A_LED_PIN, LED_ON);
            //tb 10/19/2013 patch to use Crius pin 35
            digitalWrite(A_LED_PIN_EXTERNAL, LED_ON);

```
    }else{
        digitalWrite(A_LED_PIN, LED_OFF);
        //patch to use crius pin 35
        digitalWrite(A_LED_PIN_EXTERNAL, LED_OFF);

    }
}else{
    // armed
    if(!ap_system.arming_light) {
        ap_system.arming_light = true;
        digitalWrite(A_LED_PIN, LED_ON);
        //patch to use pin 35
        digitalWrite(A_LED_PIN_EXTERNAL, LED_ON);
```

in motors.ino
    // update leds on board
    update_arming_light();
    //tb patch to use external LEDs on Crius pin 35
    digitalWrite(A_LED_PIN_EXTERNAL, LED_ON);

in system.ino
    // setup IO pins
    pinMode(A_LED_PIN, OUTPUT);                                 // GPS status LED
    digitalWrite(A_LED_PIN, LED_OFF);
    //tb patch to use Crius pin 35 for external LEDs
    pinMode(A_LED_PIN_EXTERNAL, OUTPUT);        // Set external pin 35 to drive LED
    digitalWrite(A_LED_PIN_EXTERNAL, LED_OFF);

 */

**Comment by bmizes** [comment]
Thomas, 

The Crius 1.1 board does not have pin 34 and 35, or at least mine doesn't.  The last available pin is 33.  Any suggestions on how I might go about getting external leds to work for both arming and GPS lock on this Crius 1.1 board?  I'm using the latest 3.0.1R4 firmware.  Have you done any additional coding to be able to use external leds with GPS lock.  Thanks.

**Comment by thomasbutler** [comment]
Yes it does.

**Comment by thomasbutler** [comment]
Read my comments. I use the pin 34 pin. All Crius boards v1.1 have 34 and 35.

**Comment by bmizes** [comment]
Thomas,

I assume the pins 34 and 35 that you are referring to are the two solder
pads above pin 33.  These 2 pads are to be used to supply external power to
the board if you use GPS or a number of other added devices.  Are you using
these two solder pads for your pins 34 and 35?  Below is a picture of the
Crius 1.0 (and 1.1) board and as you can see there are no pins labeled 34
and 35, although there are the two solder pads above pin 33 along the left
side of the board.  If you could confirm which part on the board you are
using for pins 34 and 35, I would very much appreciate it.  I am trying to
dissect the current code so i can use A4 and A5 for GPS and arming lights,
but in the meantime, I'd like to be able to duplicate what you did to at
least have arming lights.

Thanks.

Barry

[image: Inline image 1]

On Wed, Feb 19, 2014 at 1:59 AM, thomasbutler notifications@github.comwrote:

> Read my comments. I use the pin 34 pin. All Crius boards v1.1 have 34 and
> 35.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MegaPirateNG/ardupilot-mpng/issues/22#issuecomment-35474444
> .

## 

Barry Mizes
7001 Washington Ave.
St. Louis, MO 63130

314-721-1841 voice
314-484-0504 cell

bmizes@yahoo.com
