### ISSUE TITLE
Constant Beeping

### ISSUE THREAD

**Issue by thorphar** [MegaPirateNG/ardupilot-mpng#23]
When i start up my quad it beeps once then starts beeping and never stops.

**Comment by smurfy** [comment]
What exactly beeps? the esc's? the only time i had an esc beeping constantly was the time i did not connect the pwm/signal wire to anything (flight controler or rc receiver)

So maybe you forgot connecting the esc's to your flight controller or you connected them wrong. (mixed up ground and signal, on wrong port whatever)

My ESC did not beep, even after flashing a Quad config with 8 motors connected on all outputs.

You also should provide more informations on what hardware do you use.

like:
- which board
- which esc's
- simonk or not
- version of 3.0.1 or 3.1 ...

**Comment by thomasbutler** [comment]
I had the same problem.  For me, it required recalibating my RC transmitter in MissionPlanner.  After that, all is well.
