### ISSUE TITLE
[question] HMC5883L on Crius v2

### ISSUE THREAD

**Issue by iem4voos** [MegaPirateNG/ardupilot-mpng#27]
There is something to do to access to HMC5883L i2c on Crius AIOP v2? 

i ran the Ap_compass example but no luck, write is ok but read nothing
scanning i2c bus only the baro and the imu appears.

I know you have the schematic of this board and know a lot about, so i hope you can give me some pointers to understand better this nice board.

Is the compass attached directly to the imu or if i can't scan it mean simply my compass is not working?

one more question about the board where can i find the portmapping of the crius?

I appreciate very much your work!
Thanks, 
Michail

**Comment by SirAlex** [comment]
Ap_compass example will not work. Because 5883 connected to MPU6000 and before use compass you must properly configure MPU6000 to passthru I2C bus.
i2c_spy.pde from MPNG distro will detect 5883 even it connected via MPU6000. It properly configure MPU6000 so 5883 must be detected by i2c_spy

**Comment by iem4voos** [comment]
got it, it works thanks!

if you have time and if it not violate your NDA can you share some knowledge about the crius v2?
