### ISSUE TITLE
Running Mission Planner on a Linux Machine

### ISSUE THREAD

**Issue by thorphar** [MegaPirateNG/ardupilot-mpng#28]
Could any one give me instructions on how to install mission planner on a linux machine?

**Comment by edw00d4711** [comment]
Hello thorphar,

that is not an issue related to mpng.
Please close this thread.

If you google you will find some solutions.

Thank you!

**Comment by ralphwu** [comment]
You can try APM Planner 2 for Linux which is still alpha. It is customer Qgroundcontrol for APM.

https://github.com/diydrones/apm_planner
