### ISSUE TITLE
RFC: Documentation for MPNG

### ISSUE THREAD

**Issue by smurfy** [MegaPirateNG/ardupilot-mpng#31]
After writing my small documentation for my ArduPlane fork (https://github.com/smurfy/ardupilot-mpng/wiki/ardupilot-mpng-fork-for-arduplane)

I thought about creating the same for ArduCopter. I'm thinking about creating a separate repository for documentation.

Ideas / Thoughts:
- Only document MPNG releated stuff, everything else with a link to the offical ardupilot documentation
- Use separate git repository (allows users to contribute to documentation but with some kind of approval concept via pull requests)
- I would use http://pages.github.com/  with maybe a custom domain

**Comment by thomasbutler** [comment]
smurfy, It's my feeling MPNG's deviation from the ArduCopter firmware should only be for selecting unsupported FC boards.  We don't want to lose out on the excellent work being done by APM DIY developers.  Forking the code too far creates a very significant effort in reconciling the differences when a major update is created in a software package.  KISS is my mantra and Sir Alex has done well by creating a "HowTo" page.  I had no problem making changes for my Crius and uploading the firmware.  It works PROVIDED users read it.  Perhaps adding links to the APM pages for vibration, FPV, setting PIDs for loiter, and all that good stuff that the APM users have already created would be helpful.

**Comment by smurfy** [comment]
> Perhaps adding links to the APM pages for vibration, FPV, setting PIDs for loiter, and all that good stuff that the APM users have already created would be helpful.

Yea thats exactly what i think and want to do.

> Forking the code too far creates a very significant effort in reconciling the differences when a major update is created in a software package

But some stuff differs from the original ardupilot and i would like to document that changes up to date and nicely. 
Also i want to give the Documentation the same (or a similar) feel like the original has. Thats why i took the time to adapt the connection readme of arduplane and altered it that it fit the connection to my crius.

> KISS is my mantra and Sir Alex has done well by creating a "HowTo" page.

i know the old documentation at google code and while it contains many information its sadly no longer up to date and by far not so user friendly as the new documentation at ardupilot.com. (which is fairly new).

I just wanted to start this request for comments to evaluate if @SirAlex approves of this idea or maybe even had his own ideas tackling the documentation subject.

I just noticed that over the past couple of days some issues got created here which are related to simple not reading the documentation. the reason could be the person was just too lazy to do so or maybe, the documentation could not be found / understood.

**Comment by SirAlex** [comment]
Of course if someone will spend some time to improve my documentations (How-Tos) it will be great.

I'm prefer to use existing website www.megapirateng.com, I can give access rights for Tech writers. This site is powered by WordPress so it's easy to write docs.

**Comment by smurfy** [comment]
Ok,
i spend the last couple of hours testing and writing the docu using github pages.
http://smurfy.github.io/ardupilot-mpng-documentation/index
Everything gets automatically generated based here:
https://github.com/smurfy/ardupilot-mpng-documentation

I will start the motor connection page with images for APM:Copter tomorrow.

Reading and rewriting the documentation gave me some stuff i want to document but i don't know how the thing actually works :)
1. How does updating the bootloader actually works? 
   what needs to connectet where and so on :) 
2. On the official APM Board i need to add a jumper bridge between two ports if i want to use PPM for the RC Input. Do i need that too or is it enought to just connect Pin A8 ?
3. Custom domains for the pages is possible. i would suggest http://docs.megapirateng.com

On a side note, i would love to maintain the documentation and apm:plane. for that i would suggest creating a github organisation and move the main mpng repository and the docu repository to that organisation.

I then could push my arduplane branch to that repo too. but before doing that we should meet up with other possible contributors and define some sort of rules for branch names etc. (like ardupilot does it with the diydrones organisation)

**Comment by smurfy** [comment]
Ok i think i'm done for now.

Waiting for feedback and future instructions :smile:

**Comment by SirAlex** [comment]
@smurfy ,
Are you seen my comment above?

I want to collect all docs/how-tos on my site. I will give write access to it, if someone will contribute docs to it.
I'm just don't want to be related to 3rd party sites like GitHub, GoogleCode.

If wordpress not useful to maintain docs, I can install other system like DocuWiki or just MediaWiki... or...?

**Comment by smurfy** [comment]
@SirAlex Yes i understand that you don't want to depend on 3rd party sites. I also keep a seperate repository mirror locally.

I don't really like wiki's for documentation, but i'm very happy with the git repository and the markdown files.
Keeping everything in git has many advantages, like easy ways to contribute and the fact that everyone who clones the repro has a local copy of the documentation.

If you want to host the documentation on your server i'm fine with it. 
If you are hosting it on a root server you can use "https://github.com/mojombo/jekyll" to render the markdown to html (this is what github pages uses and how its currently works) or i could create a small php application which uses a clone of the docu repository.

I also like some way to automatically update the site either a simple commit hook from the docu repository or a cron script on the server which pulls the latest changes from the repro and updates the site.

**Comment by SirAlex** [comment]
@smurfy  OK, repo was moved to new place MegaPirateNG.

Could you please, transfer Docs to this repo, I will grant access rights to you for new place.

**Comment by smurfy** [comment]
Sure will do, as soon i get access.

**Comment by SirAlex** [comment]
So what kind of access you need to move docs? Is it required separate repo for docs?
I can create new repo MegaPirateNG/Docs, so I can give write access for all who want to contribute help pages.

**Comment by smurfy** [comment]
i either need admin access to the organisation or a new repro with team write access (like flashtool). to push the repro.

**Comment by SirAlex** [comment]
MegaPirateNG/Docs was created, welcome :)

**Comment by smurfy** [comment]
Ok, pushed stuff and docs now works:

http://megapirateng.github.io/Docs/

i'm closing the issue now.
