### ISSUE TITLE
PreArm: Bad Gps Pos

### ISSUE THREAD

**Issue by nelsonlee** [MegaPirateNG/ardupilot-mpng#36]
Hi SirAlex,

I have this (Multiwii and Megapirate AIO Flight Controller w/FTDI (ATmega 2560) V2.0) running on firmware 3.1R4, first setup is ok, after that i try it said PreArm: Bad GPS Pos!

May i know what i have to do?

![prearm bad gps pos](https://f.cloud.github.com/assets/5784885/1414928/4bd61a4a-3ebf-11e3-9093-491207cd4653.jpg)

**Comment by SirAlex** [comment]
Please, do not use version from master. Current beta version is 3.0.1 R3!

P.S. Regarding your question, you must disable FENCE (It's based on GPS, but you have no GPS, so it can't work)
