### ISSUE TITLE
Physicly connected a NEO-6 GPS to my "HK Multiwii and Megapirate AIO Flight Controller w/FTDI (ATmega 2560) V2.0" with MPNG V3.0.1 R2 but the FC does not see the gps...

### ISSUE THREAD

**Issue by laasmooi** [MegaPirateNG/ardupilot-mpng#37]
It is the older type with 6 wires.
I do have a red LED and an alternating blue LED, meaning it sees satts. 

But how do I let know the FC that a GPS is connected?
With earlier versions it was easy: Just do it in Arduino (in config.h unless I'm wrong) but I do not see that option any longer.

I am totally confused...

...Sorry, I solved it already.

**Comment by smurfy** [comment]
> ...Sorry, I solved it already.

if you solved it already, please close the issue, thank you
