### ISSUE TITLE
PIRATES_DROTEK_10DOF_MPU not supported enought ?

### ISSUE THREAD

**Issue by wareck** [MegaPirateNG/ardupilot-mpng#39]
I fly with megapirate 2.9.1 and a PIRATES_DROTEK_10DOF_MPU board.
with this version, I can not use it anymore ?
Or there is something to do ?

Olivier

**Comment by SirAlex** [comment]
Sorry. It not supported right now. Maybe in future if we solve basic problems with our CPU...
