### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by rollfeldraser** [MegaPirateNG/ardupilot-mpng#40]
Hi,

I set up my Arduino and Sketch like it was written in the manual from megapirateng.com.
But after a few seconds during the compiling I get the message:
"MAVLINK_MSG_ID_MISSION_WRITE_PARTIAL_LIST was not declared in this scope" or sometimes there's something with "run_cli".

Please help me!

**Comment by edw00d4711** [comment]
Start from scratch. Double check each step.
http://www.megapirateng.com/compile-mpng-sources/

**Comment by rollfeldraser** [comment]
I repeated it at least three times.
Is there any video tutorial for the 3.0.1 ?

**Comment by edw00d4711** [comment]
Join here: http://webchat.freenode.net/?nick=fpvde-....&channels=%23mpng&uio=d4
Some of us speak german. I will try to help you in the chat.

**Comment by rollfeldraser** [comment]
Solved with the help of edw00d7411!
Probably it was a path created by me that was too long!
