### ISSUE TITLE
Selecting GPS_PROTOCOL any other then AUTO in APM_Config.h causes compilation error

### ISSUE THREAD

**Issue by GrzegorzKolasa** [MegaPirateNG/ardupilot-mpng#42]
Trying to complile MPNG 3.0.1 R2 and getting this error:
system:208: error: cannot convert 'AP_GPS_UBLOX

Selecting any other protocol like:
GPS_PROTOCOL_NMEA, GPS_PROTOCOL_MTK or even GPS_PROTOCOL_NONE causes same compilation error "cannot convert 'AP_GPS_XXX  (_)()' to 'GPS_' in assignment"

I CAN complie ArduCopter if define GPS_PROTOCOL_AUTO, but my ublox GPS doesn't work.

Similat issue by SirAlex;) :
https://github.com/diydrones/ardupilot/issues/477

**Comment by smurfy** [comment]
As commented in your linked issue, this has been fixed in master so the fix will be in 3.1.0 once it's stable.

**Comment by SirAlex** [comment]
This bug already fixed in R3
