### ISSUE TITLE
Strange behavior 

### ISSUE THREAD

**Issue by irynkovoy** [MegaPirateNG/ardupilot-mpng#45]
I am not sure, that this is a bug. But just want to let you know about it:
http://www.youtube.com/watch?v=zIeZitn_yLY

I brang magnet close to AIO PRO v2.0

Firmware: latest MegapirateNG MegaPirateNG 3.0.1 R2

Is it O.K.?

Pay attention on red LED. It stops blinking after magnet near compass.

**Comment by SirAlex** [comment]
Yes, this is known thing. But I cannot reproduce this on my test bench so I cannot fix it.

May you try latest beta 3.0.1-R3?

Also, I see RED double flashing - it's mean you not pass some calibration procedure. Please, connect to Mission Planner and try to ARM board, you will see error message on HUD display.

**Comment by irynkovoy** [comment]
I don't have RX/TX now, waiting for new one from HK. I am flashing it now with latest version from Git. I will calirate everything I can without RX/TX and will try this magic again :)

P.S. I am not sure. But maybe you speak Russian?

**Comment by irynkovoy** [comment]
Good news. On latest version everything is OK.
