### ISSUE TITLE
Problem compiling Arduplane 2.76 for Crius v1....

### ISSUE THREAD

**Issue by sykick** [MegaPirateNG/ardupilot-mpng#47]
When I select Crius V1 and try to compile I get error msg's about dataflash. I'm pretty sure the Crius V1 does not have dataflash, so how do you disable this so Arduplane 2.76 will compile? I checked Arducopter and this will compile fine with the same board selected.  

Many thanks,
Sykick

**Comment by smurfy** [comment]
Did you try my Fork? Because there is no arduplane 2.76 in the offical ardupilot-mpng repro.
If you did try my fork please create the issues there. 

https://github.com/smurfy/ardupilot-mpng

**Comment by sykick** [comment]
Yep sorry it was your fork I tried, I followed the instructions at: http://docs.megapirateng.com/documentation/compile

Thats when I got the dataflash errors. 

rgds,
Sykick

**Comment by sykick** [comment]
New issue created, sorry for the wrong post....
