### ISSUE TITLE
MAVLink MinimOSD signal lost in LOITER

### ISSUE THREAD

**Issue by icsss** [MegaPirateNG/ardupilot-mpng#5]
I'm loosing OSD signal when flying in LOITER. It dosn't happen in STABLE or ALT HOLD.

Check this video: http://youtu.be/LciUs0ZwbqM
- AIO PRO V1 rctimer
- On-Screen Display OSD Board MinimOSD APM Telemetry to APM 1 and APM 2 (v0.1) from goodluckbuy
- Crius CN-06 GPS Receiver v2.0 Module from goodluckbuy

Everything else seams to works just fine, perfectly actually. The LOITER in incredible precise. Only 2 flights so far.

**Comment by icsss** [comment]
Any comments on this issue SirAlex? Anyone else using a minimOSD with AIOPRO and MPNG 3.0.1 R2?
Thanks.

**Comment by icsss** [comment]
Today I lost connection to MAVLink via OSD in ALT HOLD too.

**Comment by sevet** [comment]
This happens to me on all modes as soon as i take off... as soon as i land, it is ok. I just loose the data, i still get a picture from the minimOSD, my thought is that this is a combination of problem from MPNG triggering a bug in MinimOSD-extra... 
This is a critical bug.

In between resets the OSD works and I do get data regarding my battery , rssi, altitude etc'...   but can't fly like this sadly

**Comment by SirAlex** [comment]
Looks like it's resources overusage on our platforms. CPU has not enough power to process all data and reduces refresh rate for low priority tasks.
APM also has this problem, but to reproduce it on APM, you must use Octo config and enable additional functions like Mount. Currently this discussed here: https://groups.google.com/forum/?fromgroups=#!topic/drones-discuss/xhJAD9SEO2w

I think, in new versions DIYDrones team will investigate it and make fixes to speedup code.

**Comment by sevet** [comment]
small update: on MinimOSD-extra b621 (a deprecated verion) There are no OSD crashes or resets.
On stabilized it is 100% ok, on alt hold or loiter the refresh rate of the data is very slow, about 3-4 second for update.
The question is maybe this is just a symptom of a bigger issue and how safe it flying with it like this?  the refresh problem is tolerable.

**Comment by icsss** [comment]
Did someone tried 3.0.1 R3? The main loop rate was lowered to 100Hz, maybe this fixed the OSD problem..

**Comment by qdrk** [comment]
I'm using the 3.0.1, it loses mavlink connection very frequently, so sad...

**Comment by qdrk** [comment]
If this is a resource overusage problem, can we disable some of the features to have a stable mavlink connection?

**Comment by qdrk** [comment]
Can some one advise on that?

**Comment by qdrk** [comment]
Hi SirAlex, I'm looking into your code, they are great, neat and professional, but I think the following section has something to do with the mavlink connection, can this be improved, especially the two while loops?
under /libraries/AP_HAL_MPNG/Scheduler.cpp

 void AVRScheduler::delay(uint16_t ms)
 {
     uint32_t start = _timer.micros();

```
 while (ms > 0) {
     while ((_timer.micros() - start) >= 1000) {
         ms--;
         if (ms == 0) break;
         start += 1000;
     }
     if (_min_delay_cb_ms <= ms) {
         if (_delay_cb) {
             _delay_cb();
         }
     }
 }
```

 }

**Comment by SirAlex** [comment]
@mirikle , Thanks, but actually it's not mine code. It's ArduCopter...

This is just delay function. Two whiles needed to make CallBacks (Which actually send mesages to GCS via _delay_cb function)
Also, current code doesn't use delays (Except some hardware initializations routines at startup)

> I'm using the 3.0.1, it loses mavlink connection very frequently, so sad...

It loses connection or your OSD(?) just reboots sometime?

**Comment by c-bob** [comment]
@SirAlex: have you updated th scheduler task timings in current 3.0.1r3 or in upcomming 3.1?

**Comment by SirAlex** [comment]
Updated only in 3.0.1 R3

**Comment by sevet** [comment]
Actully at some point I got it working on MPNG 3.0.1-R3 without any
delay.didn't notice when exactly, but I compile the code with everything I
can as off like the Camera gimbal.

**Comment by nl2rma** [comment]
Same problems here, on Cruis AIO v2, and mpgn3.01R2, 
First used the minimosd-extra and after arming the osd hangs. After installing the standard minimosd no hangups anymore but switching to LOITER loses communictions with mavlink.

**Comment by SirAlex** [comment]
Use MPNG 3.0.1 R3!

**Comment by nl2rma** [comment]
OK thank you, I will try this, didnt know it was good to use already, did not notished on www.megapiratesng.com homepage.
