### ISSUE TITLE
ArduPlane 3.0.1-r3 no GPS fix with custom baudrate

### ISSUE THREAD

**Issue by wacko911** [MegaPirateNG/ardupilot-mpng#50]
Custom SERIAL2_BAUD is not being used by system.pde on line 101 resulting in no gps fix if baud rate set to anything other than 38400.

Current
hal.uartB->begin(38400, 256, 16);
Fix
hal.uartB->begin(SERIAL2_BAUD, 256, 16);

**Comment by SirAlex** [comment]
Thanks, fixed.
