### ISSUE TITLE
Compass doen't work

### ISSUE THREAD

**Issue by milkseller** [MegaPirateNG/ardupilot-mpng#52]
Latest arduplane firmware. Compass doesn't work until I do restart with onboard button. Then everything goes okay until power disconnect. While trying to connect with USB, board restarts itself, and everything works OK.

Board connected with USB,
Telemetry and GPS connected.

I bet it's a software problem. Something like compass have not enough time to power up before MEGA asks it. After button reset, compass already works, and MEGA gets correct reply. 

Sorry for bad english. Thanks a lot

**Comment by smurfy** [comment]
What version of arduplane do you using? My fork or official.

What exactly mean Compass does not work?

My following answer is based on the assumption, that the compass itself works but shows wrong axis information.
The reason for that is, that ArduPlane recalibrates, acc and gyro EVERY startup.
This means you need to keep your plane plan until its fully booted. (leds A and C stops playing police car)

This could cause problems if you for example need to put the board into the plane already powered up.

With ArduPlane 2.76 you can disable the recalibration completely. You can also increase the a delay until the calibration starts to give you time putting your plane plan. (i think the delay option is already present in older version, but i'm not sure)

Edit:
if the above solution is not the problem, please provide us with more information like what board do you using.

**Comment by SirAlex** [comment]
This bug already fixed (commit 0fa02a93258325f1555749c02e9f3116c5277106) in MegaPirateNG repository . You may download it and flash again.

**Comment by milkseller** [comment]
Thanks a lot.
