### ISSUE TITLE
Loiter issue or parameter tuning needed?

### ISSUE THREAD

**Issue by jan4fun** [MegaPirateNG/ardupilot-mpng#53]
Dear,

I've loaded the V3.0.1 R3b on to my AIO V1.1 and it is working fine.
I do have a strange issue with loiter, which might be a parameter problem also.
Here it is:
When in loiter and facing into the wind, loiter is spot on, it does not move. Also RTL into the wind is great, it climbs to desired height flies to the take off point and land.

However when the quad is sideways into the wind I get toilet bowl effect after a few seconds which gets worse and have to switch back to stab.
Same issue when trying RTL

Any hints on what could be the cause or checks to be done?
Magnetic decl is set, auto compass is disabled, compass calibration is done.

Thank you

**Comment by jarmohalme** [comment]
How about compassmot calibration?

http://copter.ardupilot.com/wiki/ac_compasssetupupadvanced/#Compassmot_8211_compensation_for_interference_from_the_PDB_ESC_motors

There may be different magnetic interferences when motors fights against winds from front or side...?

**Comment by jan4fun** [comment]
jarmohalme,

Indeed!
I did a compassmot yesterday but didn't had the time yet to update my post.
After the compassmot I took it out for a spin and worked flawless even in guty winds.
Loiter and RTL are spot on now.

I will close this topic

Thank you for your feedback
