### ISSUE TITLE
Camera gimbal RC10 (pin D11) has random movement every 2-3 seconds.

### ISSUE THREAD

**Issue by Homertje** [MegaPirateNG/ardupilot-mpng#54]
I Use the HobbyKing AIOP (Crius AIOP v1.1 clone) and have issues with pin D11 output. (RC10)
I opened a issue with SSG camera servo mix stabilization, found and implemented a custom code that works (perfectly might I add) ,  however while testing it, I ran into problems.
When selecting what RC output to use Servo, only RC12 + RC8 controls the 2 servos correctly. 

The original camera gimbal pins obviously do nothing.
When using the suggested RC11(D12) + RC10 (D11), Stabilization works (both modded and original code) however RC10(D11) has a pause every 2-3 seconds in servo control and sudden random movement for another 2-3 seconds, after this random movement stabilization works again for another 2/3 seconds and the process repeats. (both in original tilt/roll code as does it have this problem with my modded code)

D6(RC6?), D9(RC?), D10 (RC?) and RC10 (D11) are unusable the only way to have 2 servo/brushless gimbal axis working is to connect to RC8 (D8)  i'm aware pins D9 and D10 are used for the sonar but i wanted to test the outputs anyway!

What seems to be the problem controlling the "original" camera pins? (D44/D45 on HK mega red - 44/45 on HK Crius AIOP v1.1 clone.) I've read about BAD experience with these pins, so does the jitter in those outputs make camera footage unusable still? Is it a possibility for future releases to bring them back?

Is it possible to maybe offload the camera code onto a secondary arduino board so PWM pins CAN be used there? (Like for instance a Arduino Pro Mini) 
A serial output of attitude of the FlightController (raw MPU output maybe) can be decoded and some math can be applied on the 2nd arduino board. This would be the best (cheapest) solution IMHO. you can even get brushless drivers in the exact same dimensions of a Arduino Pro mini, so if this is possible a lot of people will be pleased if this can be made to work. Just my $0,02. :)

**Comment by NoRCexperience** [comment]
I would vote to delete all gimbal code from MPNG. Its never been good. BCG is so cheap now its the better solution anyway. I would ASK please to make the gimbal code section now only a PPM passthrough. For those using PPM receivers, having channel 7 and 8 available as outs off the main board to feed to secondary stabilization board.

**Comment by Homertje** [comment]
why do you think these cheap FC have the pins, even the APM has gimbal pins, because it's possible to just do so! extra controllers = extra weight, extra cables and more draw on battery life. and to be sincere, why add another MPU6000 just to stabilize the gimbal?? if you'd export the mpu6050 or mpu6000 data you could make the camera gimbal controllers even cheaper as the acc/gyro chips are the most expensive parts on a controller.

because something has been neglected and grown into forgotten code should not mean you should just delete it... 
no, they should FIX it... 

Preferably since MPNG is for people who want A grade flight controller for C grade money, and is dedicated gimbal processors are not so expensive does not mean they're cheap, the SSG solution however IS cheap and it works well enough, hell it even works on a KK2.0 flight controller.

I find it kind-of crazy anyway, that the APM FlightController has the same processor as a Crius AIOP v2 but does not have the problems with processing the original APM code... also MultiWii has gimbal code working like a charm, might be useful to scrap all non MS5611/mpu6050(mpu6000) code. the bmp085 isn't reliable anyway... 
it's the new HAL way of things (AC3.0 and up) that keeps on kicking in the coder's teeth, i think.

Also when using a hex or a octo config, you would need the SAME processing power to stabilize all 6 / 8 outputs as you need to balance a quad + camera gimbal...

**Comment by SirAlex** [comment]
> What seems to be the problem controlling the "original" camera pins? (D44/D45 on HK mega red - 44/45 on HK Crius AIOP v1.1 clone.) I've read about BAD experience with these pins, so does the jitter in those outputs make camera footage unusable still? Is it a possibility for future releases to bring them back?

In previous versions this pins (44,45) uses software PWM generator, which has big jitter and consume CPU power. Now in 3.x we running out of CPU power, so I'm removed software PWM generator.
So now, there is only way to use D11,D12 pins - it uses hardware PWM.

> I find it kind-of crazy anyway, that the APM FlightController has the same processor as a Crius AIOP v2 but does not have the problems with processing the original APM code... also MultiWii has gimbal code working like a charm, might be useful to scrap all non MS5611/mpu6050(mpu6000) code. the bmp085 isn't reliable anyway...
> it's the new HAL way of things (AC3.0 and up) that keeps on kicking in the coder's teeth, i think.

Even CPU and sensors is same, the sensors in CRIUS (and all MWI like boards) connected via I2C bus which much slower than SPI bus used in APM. So same code in MPNG works slower than in APM. We just need more time to read sensor data.

**Comment by Homertje** [comment]
Allright, that clarifies all but one question: i have my board configured as tri copter (soon to be a quad) D11 has a pause every 2500ms for exactly 2500ms resets position to 0, and then resumes operation like normal for another 2500ms, and loops this process, any ideas? I have installed R3 with 8 analogue inputs. if i use output RC8 the problem does not appear. however this setup confuses me in cables a lot.

**Comment by SirAlex** [comment]
I will check this.

**Comment by NoRCexperience** [comment]
"why do you think these cheap FC have the pins, even the APM has gimbal pins, because it's possible to just do so! extra controllers = extra weight, extra cables and more draw on battery life. and to be sincere, why add another MPU6000 just to stabilize the gimbal?? if you'd export the mpu6050 or mpu6000 data you could make the camera gimbal controllers even cheaper as the acc/gyro chips are the most expensive parts on a controller"

I said the above because I HAVE used the onboard gimbal controls. Just because the chinese put pins on the board doesn't mean it will work well. My video is on TV so I need something that works not that jittery shaky mess. I tried for months and spent more than $50 trying ferrite cores, servos, etc... trying to make it work. Finally I spent $50 on a brushless setup (including the pro mini 328). I would never go back to using servos. We are LUCKY people like Alex are willing to spend the time on this. I would rather concentrate time and effort on flight, not yesterday's gimbal technology. Losing a decently built model is expensive. Many of us have lost one or more due to glitches. Fly aways, lock ups, etc... This is not Alex's fault. This happens to $1000 DJI controllers too. 

"Preferably since MPNG is for people who want A grade flight controller for C grade money, and is dedicated gimbal processors are not so expensive does not mean they're cheap, the SSG solution however IS cheap and it works well enough, hell it even works on a KK2.0 flight controller."

We cannot have every feature on every flight controller. MWI just recently got way points. KK has none of these (waypoints, gps, sonar). You cannot compare that situation. KK2.0 is fine, so if you like it why not fly it? I think you will find very few people use or want onboard gimbal control which is why I suggest removing it. Feel free to fix the code if you can. I think the SSG is a nice simple solution if it actually works.

I want a flight controller that doesn't crash because I tried to save $20. If it can do gimbal right, great, but that is a secondary concern.

**Comment by Homertje** [comment]
NoRCexperience, i don't know who or what you are but you are not in any way helping me or this issue, you might not be interested in this function, this does not mean you get to decide what is and isn't important. clearly the gimbal functions are embedded in MPNG3.x, Mission Planner and AC3.x so please, go fly your aircraft with your nice gimbal controller, and if you so NEED a stable product, buy a actual APM that will run the unmodified AC3.1 code or a NAZA and when you do, just leave this place. or just respect others who ARE interested in the functions that are available. Either way don't press your preferences on other users (such as me) tyvm. 

Alex explained it has something to do with the way chips talk to eachother on a hardware level (SPI vs I2C). 
Note: Alex explained it to me in a nice and friendly tone.  

IF you would have followed my posted issues you would have seen i already fixed the code that enables SSG servo mixing within MPNG 3.0.1 R3 and it's working fine without increasing workload for the processor. 

I was asking Why the gimbal pins were disabled, Alex explained. 
software pwm is a issue, i get that.

The issue at hand is: I noticed a problem when using the pins Alex noted to be used, A 2.5 second interval where 1 servo or motor connected to output D11 would stop working and reset to midpoint. and resuming operation. If the code already computes the compensation of roll and pitch it won't crash any FC unless there's a missed bug in the code. 

If this issue has something to do with the main attitude compensation code, you might me thanking me later I found this issue. If this has something to do with the HAL or the pin assignments, you might be thanking me sooner, because then, your $50 gimbal doesn't come tumbling down together with your malfunctioning FC crashing the whole aircraft. 

And about comparing the situation, yes they do compare, you actually run parts of the AC code on your FC as well, because MPNG is based of AC.

And funny you should say old ways, SSG is exactly 1 year old. if you call that a OLD way of gimbals....
just watch http://youtu.be/1nBJh1mt9jU and please enlighten me why this should not be an acceptable result for me... 
By the way, just saying if you fly fpv off a tv you should be using a simple camera FIXED on the body of your aircraft (without any stabilization) to prevent crashes such as the one SSG creator Crezzee experienced when switching to ACRO mode in the video posted above. if you experience to much vibration on the FPV feed (when having a fixed camera on your aircraft), you should REALLY fix (balance) your props and motors as that is cause #1 of crashing a tri, quad or other (multi)copter.

legend:

AC = ArduCopter
FC = FlightController
SSG = SuperSimpleGimbal by crezzee

**Comment by SirAlex** [comment]
Just tried to reproduce on my desk. All works fine. I'm connected two 5gr servos to D11,D12 and enabled RC10,RC11 for camera stabilization. Tried all positions and there is no any servo resets or other problems.
I'm tested on my CRIUS V1 board on latest MPNG 3.0.1 R3.

Try to disable input channels for gimbal if you enabled it. Also maybe something going wrong on HK boards, but I have no this boards, to cannot verify.

**Comment by Homertje** [comment]
Thanks for testing, i've disabled the inputs and in tricopter config it still has the same issue, will try in Quad setup end of this month (as i'm going to build myself a TBS Discovery Quad)
Quite possibly this will fix the problem or open up 1 or 2 more motor pins to run camera gimbal from. It's no big deal, just a nuisance for cable management! There's a last possibility my FC has had a malfunction from the start will test with my RED HK board this week. Again thanks for testing, I now know it's me or my hardware not a bug.

**Comment by Homertje** [comment]
HK Board does the same thing.. I give up... :P i'll be ordering a alexmos gimbal controller soon.
Although I truly admire your work SirAlex, this i2c thing is giving me problems, so I also ordered and received a APM2.5.2 copy/clone really cheap, and it does exactly what is advertised. I will still be participating where i can testing MPNG on my Crius aiop v1.1 and RED HK board, and giving feedback, so THANK YOU for your testing and hard work on MPNG!
