### ISSUE TITLE
 Is support for ITG3205 included in  mpng-3.0.1-r3  ?

### ISSUE THREAD

**Issue by Espenf** [MegaPirateNG/ardupilot-mpng#55]
Is mpng-3.0.1-r3 working with ITG3205 Triple Axis Gyro ?
 Is this IT3200 same as ITG3205?, anyway below says: Only MPU6050 supported for R2
 Is support for ITG3205 included in -r3 ?

Release Notes for MegaPirateNG 3.0.1 R2 (ArduPilot 3.0.1) 
 IMPORTANT NOTICE!!!
 IT3200 gyro doesn't supported in this version!!! Only MPU6050 supported!

(MultiWii PRO_HK_RED uses ITG3205 Triple Axis Gyro)

I have flashed my MultiWii PRO_HK_RED with 2.9.1 R6 and it seems to work, but i wonder if its wise to try mpng-3.0.1-r3 ??

**Comment by mkmitchell** [comment]
I would also like to know.  Thanks for asking this question.

**Comment by SirAlex** [comment]
Yes. R3 supported old sensors and HK board.

**Comment by Espenf** [comment]
Tnx Sir Alex,

I dont know how to close the request, but I have had my quad in the air now and it seems to work. Tnx for the good work.

I noticed by the way that when I activate mode “Land” there is no voice telling  me current mode.  Also when I try to bench-test the mode for contingency (like RTL if radio is lost) it most always try to RTL instead of land, even though I said it should perform land.  I attach my parameters in case you can tip me about setup errors or thing you want me to test.

Regards

Espen

Fra: Aleksey Kharlanov (Sir Alex) [mailto:notifications@github.com] 
Sendt: 10. desember 2013 12:03
Til: MegaPirateNG/ardupilot-mpng
Kopi: Espenf
Emne: Re: [ardupilot-mpng] Is support for ITG3205 included in mpng-3.0.1-r3 ? (#55)

Yes. R3 supported old sensors and HK board.

—
Reply to this email directly or view it on GitHub https://github.com/MegaPirateNG/ardupilot-mpng/issues/55#issuecomment-30216523 .  https://github.com/notifications/beacon/SxeVdHDMTETcz3dB8k6cHbd-HalSJ5jujK96TPCEjUp6TJyAQfv2CIRghGabokDH.gif 

---

Denne e-posten er fri for virus og uønsket programvare fordi avast! Antivirusbeskyttelse er aktiv.
http://www.avast.com
