### ISSUE TITLE
APM Plane, FBWA mode elevator control

### ISSUE THREAD

**Issue by wacko911** [MegaPirateNG/ardupilot-mpng#56]
Not sure if this is a bug or not but It's easily repeatable if some kind soul could ground test this

I'm using HK Multiwii pro (red board)  latest build but I dont think it's a board problem.

With GPS Lock: On the ground in FBWA mode with zero throttle apply full up elevator and hold and then increase the throttle. Elevator stays the same.

With NO GPS lock (or unplug GPS). Repeat above test and the elevator goes level as the throttle goes up.

I can't figure out why this would happen, is it by design or a bug. I think it's what caused a crash today while test RTL.

**Comment by smurfy** [comment]
Hi, what version of APM Plane do you using?

**Comment by wacko911** [comment]
"ArduPlane V2.74beta MPNG-R3b"

**Comment by wacko911** [comment]
It almost looks like a throttle elevator mix, its directly proporotional to the amount of throttle but I've checked every param I can think of and and throttle pitch mixes are at zero. It doesn't do it in Stabilize mode or manual only FBWA, haven't checked any other modes. 

After entering RTL circle yesterday, the plane banked right and headed for home, it started loosing a little alitiude and it was in a slight negitive pitch and the motor RPM kept increasing and it never pulled up. Switched out of RTL but it didn't disengage as when the plane was sitting on the ground the motor was still going. (Think the not coming out of RTL was my problem as when I toggled the RTL switch it stopped).

**Comment by smurfy** [comment]
Please test with: 

either
https://github.com/smurfy/ardupilot-mpng/tree/mpng_ArduPlane-2.76
or
https://github.com/smurfy/ardupilot-mpng/tree/mpng_ArduPlane-2.74b

ArduPlane V2.74beta MPNG-R3b is based on the first beta of the 2.74 release.
2.74b is the old stable of ArduPlane and 2.76 is the current stable.

**Comment by wacko911** [comment]
Ahh!! I thought I was on the latest as thats what the link take me to on the main MegaPirateNG build (3.0.1r3). I didn't see the fork!

Have compiled 2.74b no problem but cant test it tonight as spooling up the motor is going annoy the missus.

Tried to compile 2.76 but not sure if the HK multiwii board is suported yet? I get compile errors when I select it (it does compile as crisus v2 and v1, just not HK red board)

ArduPlane:195: error: 'AP_Baro_BMP085_MPNG' does not name a type

**Comment by smurfy** [comment]
ok, i will check the compile issue and fix it. 

Edit: fixed the compile issue

**Comment by wacko911** [comment]
Thanks Smurfy. Updated to 2.76. The elevator thing still seems to be the same. Guessing it must be a feature and not a bug. Can't quite understand why it would behave this way though. Either way its a APM:Plane problem not a MPNG problem.

Will try it in the air and see, seems to be a few changes from the firmware I was on so maybe it will just work this time. Just very nervious flying now after the first crash I tend to get scared and flick out of RTL when it might be fine if I just leave it.

**Comment by smurfy** [comment]
I tested my plane yesterday indoors by just moving it in my hand. the elevator, ailerons and rudder responded correctly (it tried to correct the position against my movement). i'm currently not able to test my plane outdoors

I'm not sure maybe its a sensor problem. I guess you are aware that the plane always recalibriate the gyro on power up? maybe the board is not plan while startup or there is a problem with the sensors with the hk board.

**Comment by wacko911** [comment]
If you want you can test this indoors.

Switch to mode fbwa.
Pull back on the elevator with then plane level and keep the elevator at
full deflection.
Apply throttle.

When there is a GPS fix, nothing happens the elevator.

When there is no GPS fix the elevator does down.
