### ISSUE TITLE
Auto Tune support 3.0.1 R3

### ISSUE THREAD

**Issue by nelsonlee** [MegaPirateNG/ardupilot-mpng#58]
May i know Auto Tune support 3.0.1 R3 or not?

**Comment by smurfy** [comment]
Autotune is NOT supported by 3.0.1.

Autotune is a new feature of arducopter 3.1 which is not stable released yet.
Once its stable released we can think about getting it working with mpng hardware.

**Comment by rotcehdnih** [comment]
Its a stable build now so maybe they will start working on it. i have started moving over just the auto-tune part to rc4 but currently dont have much time , might try to finish that tonight

**Comment by smurfy** [comment]
@rotcehdnih rc4 (current master of mpng) is not really stable you should not try to fly it. please use 3.0.1 which is more stable.

As SirAlex metioned here #57 and elsewhere, there are still some general CPU performance problems (3.1.0 and 3.0.1) and he is working on it. after this is fixed it should be relativly easy to update to 3.1.0, if no other problems arises.

**Comment by rotcehdnih** [comment]
sorry just to confirm do you mean i should be using R2 – Public Release?

**Comment by smurfy** [comment]
Yes 3.0.1-RC2 or 3.0.1-RC3 (via flashtool or git download) http://docs.megapirateng.com/documentation/compile
