### ISSUE TITLE
Compass 30 degrees off

### ISSUE THREAD

**Issue by mkmitchell** [MegaPirateNG/ardupilot-mpng#59]
I have a HK Red Board running MegaPirateNG.
In both 2.8r3 and the latest 3.0.1r3 (downloaded today) my compass shows North 30 degrees West of where it should be.  .  I have performed the accel calibration and compass calibration correctly (according to multiple youtube videos).  I have also turned auto declination off and entered it manually.

Is this an instance where I would need compassmot?

Any suggestions?  Thanks

**Comment by jarmohalme** [comment]
Can you fly normally? How LOITER-mode works? Can you tune compass -30deg to get right readings, and then test flying and LOITER again.

**Comment by mkmitchell** [comment]
Thanks for the response.  I couldn't get any of the modes to work successfully.  I've tested loiter without success as well as a small guided route and it shot off in a different direction.  RTL hasn't worked either.  I would love to tune the compass but am unsure how.  I'm guessing it's somewhere in the config.h file?

**Comment by SirAlex** [comment]
Please, try to erase EEPROM and start from scratch. To erase, open Terminal in Mission Planner, enter `setup` command and than `erase`, after board reboot, do all calibrations again.
Also double check, magnetic declination.

Compassmot will help only in case, if compass goes wrong when you increase Throttle

**Comment by mkmitchell** [comment]
Thanks for the advice.  These are the steps I took  in Misison Planner 1.2.88:
Erased EEPROM and reboot via terminal
Connect again
I'm using a FTDI adapter to connect since I broke off my usb port.
Mandatory Hardware > Compass.
Check declination (Jackson, MS) 0 degrees 36 minutes W
Uncheck auto dec and enter declination.
Hit live calibration.  Point each side of the board to the ground and wave it around in a small circle for about 5 seconds.  Sometimes I do a side more than once.  I get offsets 76 -34 7.
Accel Calibration > Go through steps  > calibration successful.

I go back to Flight data and point the front of the board North.  The Flight data shows that it is pointing at 100 degrees.

**Comment by mkmitchell** [comment]
If I change my Compass orientation to Manual Rotation_YAW_135 it appears to correct the compass.  Is this a good approach or should I change something in the advanced parameters?

**Comment by jarmohalme** [comment]
Can you try compass live calibration outside your house? My Rctimer2 boards compass goes crazy indoors just by opening fridge door couple meters away. After that I have done all compass calibrations outdoors.

**Comment by mkmitchell** [comment]
I'll give that a shot tonight.

**Comment by mkmitchell** [comment]
Over the weekend I got to play around a bit.  I tried calibrating outside but the compass was still off.  I ended up setting the compass orientation to YAW 90 degrees and performing the calibration after that.  The compass is currently in the correct direction!
