### ISSUE TITLE
Tri-copter 3.0.1 R3 ( and 3.0.X )

### ISSUE THREAD

**Issue by gio-loky** [MegaPirateNG/ardupilot-mpng#69]
Hello,the tail servo command does not return to the neutral position when disarm.
The configuration of the motor connections to the board in the documentation is incorrect. The engine in the upper left has to be connected to output 2, not to the 6.
Thanks for your great job

**Comment by SirAlex** [comment]
> the tail servo command does not return to the neutral position when disarm.

Fixed in 3.0.1 R3

> The configuration of the motor connections to the board in the documentation is incorrect. The engine in the upper left has to be connected to output 2, not to the 6.

Updated manual.

Thank you.
