### ISSUE TITLE
LOITER went crazy with 7 or less sats

### ISSUE THREAD

**Issue by icsss** [MegaPirateNG/ardupilot-mpng#7]
I've made some further tests today, it was windy and LOITER went crazy with 7 or less sats. Later, when I had over 9-10 sats everything went smooth again.

Also, loosing GPS FIX in LOITER causes the quad to bank and fly away at max speed.
(GPS FS is set to off).

**Comment by icsss** [comment]
"An hdop value of 1.5 (displayed as 150) or lower is very good. Over 2.0 (i.e. 200) indicates a bad position value. The number of satellites falling below 9 is also bad. A significant change in these two values often accompanies a GPS position change." 
from: http://copter.ardupilot.com/wiki/common-diagnosing-problems-using-logs/#GPS_glitches

Does this mean no LOITER, RTL, etc.. with less then 9 sats or a hdop>2?

**Comment by SirAlex** [comment]
New AC(MPNG) 3.1 will have GPS glitches filter. So if GPS coords went far from current location, if will filter it out.
Also, it is good idea to enable GPS FailSafe.
