### ISSUE TITLE
Crius AIOP V2 - MPNG 3.0.1 R3

### ISSUE THREAD

**Issue by Flackinson** [MegaPirateNG/ardupilot-mpng#70]
Hi,
I compiled and uploaded Arducopter MPNG 3.0.1 R3 into my Crius AIOP V2 and I am having problems with the flight modes. For certain modes (Loiter, RTL, Circle...), even if I select them in Mission Planner (1.2.90 build 1.1.5100.32953) they are not activated in the board for some reason (see screenshot). Looks like the values are correctly stored in the eeprom but for some reason they can not be activated and Stabilize is activated instead.
Is anyone having this same problem?
Thanks,
Alvaro
![apm_planner](https://f.cloud.github.com/assets/6297219/1829649/9334f3be-72e7-11e3-91aa-229fc71103bc.jpg)

**Comment by Homertje** [comment]
Does your FlightController have a GPS module attached? And does your GPS have a 3D fix?
If not: loiter, circle and RTL/RTH modes need GPS (and GPS coordinates) to work, if there's no GPS FIX, the FlightController will default to stabilize, so in case of GPS LOS your aircraft will not fly off in a random direction.
So test again when you have a GPS + 3D fix, i'm pretty sure it will work then.

(FIX = just that it's receiving data from satellites, and forwarding the data to the FlightController in a way the FlightController understands.)

**Comment by Flackinson** [comment]
Hi Homertje,
that was the problem. Sorry I didn't know that. I have tested it now with a 3D Fix and it is working just fine. Thanks for your help and happy new year.
