### ISSUE TITLE
Cannot arm in 3.0.1 R3 when internal compass is disabled

### ISSUE THREAD

**Issue by quadmax66** [MegaPirateNG/ardupilot-mpng#73]
I want to use an external compass. So I disabled the internal compass in AP_IntertialSensor_MPU6000_I2C.cpp.
After that I couldn´t arm the copter.
I did all necessary calibrations (Mag, ACC, Radio). Even when i disable the prearm-checks it is not possible. When I upload 3.1 R5 (from hexbub) all is working. 
But I do not want to use this "inofficial" version because of the CPU overload issue. 
My board is a Witespy Multiwii Pro 2.0. 
Best Regards,
Max

**Comment by gamegrd** [comment]
Look here when you try to arm 

![4](https://f.cloud.github.com/assets/3184855/1857310/10a048ac-7771-11e3-8558-bb2e1a65d395.jpg)

It will tell you why cannot arm

**Comment by quadmax66** [comment]
After erase and reset via Missionplanner terminal i could see a message prearm "low voltage".
I found a workaround here: "http://www.rcgroups.com/forums/showthread.php?t=1752719&page=134":
Add #define BOARD_VOLTAGE_MIN 3000 // 3 V instead of 4.3 V in  APM_Config.h
