### ISSUE TITLE
AutoTune

### ISSUE THREAD

**Issue by polleke1949** [MegaPirateNG/ardupilot-mpng#75]
Not really an issue, but I just want to know.
Is it possible to perform autotuning in MPNG 3.0.1 R2 Public Release?

**Comment by sosko71** [comment]
You need MPNG 3.1

**Comment by nelsonlee** [comment]
Will this MegaPirateNG 3.1 Beta already have Auto Tune?

**Comment by polleke1949** [comment]
"Will this MegaPirateNG 3.1 Beta already have Auto Tune?"
No it has not.
TIP look at: http://www.rcgroups.com/forums/showthread.php?t=2029944
Be carefull though!

**Comment by smurfy** [comment]
You can also take a look here #58 

Also the current MPNG master or 3.1beta branch is now based on the release version of arducopter 3.1 but not as stable as the 3.0.1R3 release, but should have autotune. (not tested by me)

**Comment by SirAlex** [comment]
AutoTune feature will be available in 3.1 Release. Currently it's not stable, so I'm not recommend to use it.
