### ISSUE TITLE
Tricopter 3.0.1 R3 Servo

### ISSUE THREAD

**Issue by BOBNa** [MegaPirateNG/ardupilot-mpng#77]
No pulse on 7 and always high when measured with scope. Servo does not move when yaw stick moved.  

In "AP_MotorsTri.h" I found this code.

// tail servo uses channel 7
# define AP_MOTORS_CH_TRI_YAW    CH_7

and motor mapping image also connect to 7.

Wrong?

If servo is connected to 6 it works fine.  All pulse 5,6,3,2 are same refresh rate(490Hz). 

But I still not sure about motor mapping for Tri because  my TRi can't fly.

**Comment by smurfy** [comment]
something got changed with the tri-copter recently 5a7fe8517acce24af53f695bf3fb5c44d70af1e3 the servo should stayed the same.

Also for reference here is the ticket: #69

@gio-loky it seems you also use a tri copter can you confirm that with the latest R3 the servo channel uses pint 6 instead of 7 ?

**Comment by SirAlex** [comment]
I'm recently worked on other bug (already fixed) with tri-copter servo and it works fine on pin D7. I'm thinking you are not changed firmware in TRI mode via APM_Config.h and it still working in QUAD mode.

**Comment by BOBNa** [comment]
Thanks,
I follow this link http://docs.megapirateng.com/documentation/general_configuration
I will try to re-flash firmware again.

**Comment by BOBNa** [comment]
OK after re-flash firmware it works fine. I don't know what is wrong with my previous APM_Config.h.

For now here is the result.
7 = Servo, 50Hz on scope  OK
2 = motor left front(see from tail) 490Hz  OK
5 = motor right front(see from tail) 490Hz  OK
3 = tail motor, 490Hz  OK

Many thank.
