### ISSUE TITLE
Wireing MPNG Plane 2.76

### ISSUE THREAD

**Issue by icsss** [MegaPirateNG/ardupilot-mpng#79]
Where can I get the wiring for MPNG Plane 2.76?
1. servo outputs
2. motor output
3. gps
4. airspeed sensor
5.  voltage and current sensor
6.  minimOSD
7. BT
8. MPNG Plane 2.76 supports external mag?

I'm migrating from MPNG Copter 3.0.1R3 to MPNG Plane.

**Comment by icsss** [comment]
Is this valid for MPNG Plane 2.76?
http://static.rcgroups.net/forums/attachments/4/5/6/8/8/6/a5582871-6-ARDUPLANENG%202.5R5%20HK%20Crius%20AIOP%20v2%20%281%29.jpg

Where is the airspeed sensor connected? Thanks!

**Comment by smurfy** [comment]
For servo and motor take a look here: http://docs.megapirateng.com/documentation/connecting_components_plane
There could be a problem with mode 1 rc's take a look here: #71 

Gps, BT and Minim Osd same as copter

Airspeed and voltage will be connected via analog pin's (i only tested voltage/current, i own an airspeed sensor but did not test it yet)  the analog pins should be the same as copter and which pin could be found in the offical documentation.

About external mag i don't know. if copter supports it, maybe :)

I'm also in the process releasing 2.77

**Comment by icsss** [comment]
Thanks!
Is it safe to power the servos via FC? Or should bring [5V and GND] from a external 5V power source? (I use an external UBEC to power the FC AIOP v1).

I have 4 digital servos that might pull more current...

**Comment by smurfy** [comment]
I use the power of the ubec (with closed jumper) but i use the stock bixler 1.1 servos.
I also only connect the signal wire to my motor's esc.
And i have a capacitor to hopefully prevent brownouts.

**Comment by icsss** [comment]
Where do you power the FC? via an free ESC output, 5V and GND?

**Comment by smurfy** [comment]
i connect the UBEC to the external power supply connection of the crius 2 board.

Normally you should remove the jumper from the motor/servo outputs. but if you do so there is no supply on the motor out pins. so i kept the jumper in place to supply the servos as-well.
and only use the signal line to the motor that the ubec of the esc don't make problems.

**Comment by icsss** [comment]
Very good idea! Thanks!
The only problem is the current pulled by the digital servos. It might be to much for the FC board to manage..

**Comment by icsss** [comment]
What Arduino version should I use to upload MegaPirateNG - APM:Plane 2.76?
The "special version of the Arduino" used for copter 3.0.1 R3?

Is there a help page for the changes of the code needed to accommodate the AIOP, gps, etc..?

**Comment by smurfy** [comment]
yea the special version or you can use the flashtool

**Comment by Hwurzburg** [comment]
Sorry if this is the wrong venue to ask a question about Plane:MegapirateNG...if it is, tell me where to go (I dont invite many to do that!)...but I have a Cirus V2 AIOP from RCTimer...I hope to use it on a conventional plane(Bixler)..my questions about the current release are:
1. Is it stable for this aircraft?if not, which release?
2. I want to use a main batt voltage detect(4:1 divider) and RSSI (0-3V)...can I use the analog pins and assign them with MP like I do in APM2.5?any suggestions on which pins I should use?

I will be using CPPM input, and UBEC on input side, ESC's BEC to drive output side, motor, micros on rudder,ail, and elev...6 pos flight mode switch(using ER9X tx type), inverted switch(it works in MPng right?)...and MINIMOSD and radio telem...have a CN-06 gps...

anything not in the docs I should know? (I have been flying APM in plane and copter for a while)
thanks

**Comment by icsss** [comment]
"Airspeed and voltage will be connected via analog pin's (i only tested voltage/current, i own an airspeed sensor but did not test it yet) the analog pins should be the same as copter and which pin could be found in the offical documentation."

For copterNG the voltage/current sensor is connected to A1/A0 pins. Are these the correct pins for planeNG too ?

**Comment by smurfy** [comment]
> For copterNG the voltage/current sensor is connected to A1/A0 pins. Are these the correct pins for planeNG too ?

I use A1 and A2 (http://plane.ardupilot.com/wiki/common-using-a-current-sensor/)

**Comment by Hwurzburg** [comment]
Philipp, any responses to my inquiry? thanks

**Comment by smurfy** [comment]
@Hwurzburg 
i'm new to mpng and planes. (i use multiwii for my copter).

I bought a bixler 1.1 and tested arduplane with mpng only indoors. (bad weather and finding time to test flying with a buddy of mine which flown planes before :))

All my Indoor tests worked great. the plane moves the servos as it should. don't know who flown their plane successfully.

> 1. Is it stable for this aircraft?if not, which release?

you should test 2.76 (i try to compile 2.77 and do some indoor tests with it)

> 1. I want to use a main batt voltage detect(4:1 divider) and RSSI (0-3V)...can I use the analog pins and assign them with MP like I do in APM2.5?any suggestions on which pins I should use?

i don't know about RSSI but the voltage divider should work like in APM 2.5. The Analog Pins should be the same as with the APM 2.5. So A1 for voltage.

> I will be using CPPM input, and UBEC on input side,

CPPM is supported and the default

> inverted switch(it works in MPng right?)

what do you mean by that?

> MINIMOSD and radio telem...have a CN-06 gps...

i did not test minimOSD (mine is flashed with rushosd for multiwii) but i tested 3dr Radio (rctimer clone) and the CN-06 GPS module from RCTimer with a crius v2

**Comment by smurfy** [comment]
@icsss Is this issue still unresolved or can it be closed?

**Comment by icsss** [comment]
I'm successfully using AS sensor, Current/Voltage sensor, external MAG, GPS, minimOSD, BT and everything works good.

The only problem is a bad compass health error but it it seams not to affect the flight characteristics.
