### ISSUE TITLE
Cant setup board type in arducopter 3.0.1 R2 ... 

### ISSUE THREAD

**Issue by PieroCapredoni** [MegaPirateNG/ardupilot-mpng#82]
Hi.. im trying to load the new MPNG 3.0.1 R2 in my AIOP V1 board.  First step its to set up APM_config.h in arduino, but board selection its not longer supported there.. syas to include in some config.mk.... I dont know the procedure to setup this new cersion.. its waaayyy different to my actual 2.8R3 release setup... con someone help me?

**Comment by SirAlex** [comment]
Hi,
First of all, use 3.0.1 R3. Second, follow instruction here: http://docs.megapirateng.com/documentation/flashtool

**Comment by PieroCapredoni** [comment]
Thank you very much....

**Comment by PieroCapredoni** [comment]
This project is better every day. Congrats Sir Alex!!!
