### ISSUE TITLE
Mission Planner complete tutorial....

### ISSUE THREAD

**Issue by PieroCapredoni** [MegaPirateNG/ardupilot-mpng#86]
Hi all... I want to REALLY understand and apply all the powerfull functions in the MP.. where I can find a complete manual or tutorial for this??

**Comment by BOBNa** [comment]
mpng is a modified version of arducopter, so MP tutorial for mpng = MP tutorial for arducopter.
http://copter.ardupilot.com/wiki/common-using-a-ground-station/
