### ISSUE TITLE
missionplanner, reading parameterlist failed

### ISSUE THREAD

**Issue by jobinhoo** [MegaPirateNG/ardupilot-mpng#9]
Board is HK MultiWii Pro + MTK and now is MPNG2.9_R5 installed. 
have problem by using MPNG3.0.1_R2: MissionPlanner read parameter list failed. Stoped after : "Got Parameter ACRO_BALL_PITCH" and green bar about 50%.

**Comment by SirAlex** [comment]
HK MultiWii Pro is not supported in 3.0.1 R2, wait for R3 version.
