### ISSUE TITLE
MPNG 3.0.1 R4 release notes missing?

### ISSUE THREAD

**Issue by ralenekov** [MegaPirateNG/ardupilot-mpng#97]
Release notes for 3.0.1 R4 are missing from the source branch. Can you please upload them? What are the improvements in this version? Is it only the support of the Paris v5?

3.0.1 R3B is awesome and I just want to know whether to update or not (AIOP v1). Thank you very much!

**Comment by smurfy** [comment]
It's paris v5 support and some gimbal fixes.

https://github.com/MegaPirateNG/ardupilot-mpng/compare/mpng-3.0.1-r3...mpng-3.0.1-r4

**Comment by ralenekov** [comment]
That's the confirmation I needed :) Great, thank you!
